Connected to venv_nadlan_311 (Python 3.11.13)

In [1]:
print(f"Requested date range: {dates_range[0]} -> {dates_range[1]}")

NameError: name 'dates_range' is not defined

In [2]:
from etl_sources.mizrachi_reader import load_mizrachi_tables

In [3]:
path_to_folder = r'C:\Users\shai\Documents\personal\personal_projects\ynab-israel-consolidator\private_data\incoming\bank_mizrachi'
dates_range = ("01/01/2026", "01/03/2026")

In [4]:
loaded_tables = load_mizrachi_tables(folder=path_to_folder, recursive=False)
print(f"Loaded files: {len(loaded_tables)}")

for table in loaded_tables:
    print(f"\nFile: {table.path.name} ({table.extension})")
    df_pending = table.dataframe
    print(df_pending.head())

if dates_range:
    print(f"Requested date range: {dates_range[0]} -> {dates_range[1]}")

Loaded files: 1

File: AccountActivity (1).xls (.xls)
                0          1                    2               3       4  \
0    יתרה בחשבון:   29856.69             לתאריך -  05/03/26 23:15     NaN
1    מסגרת אשראי:   20000.00                  NaN             NaN     NaN
2  תנועות אחרונות        NaN                  NaN             NaN     NaN
3           תאריך  תאריך ערך            סוג תנועה            זכות    חובה
4        10/12/25        NaN  ביצוע הוראת קבע (י)             NaN  600.00

           5       6            __source_file  \
0        NaN     NaN  AccountActivity (1).xls
1        NaN     NaN  AccountActivity (1).xls
2        NaN     NaN  AccountActivity (1).xls
3  יתרה בש"ח  אסמכתא  AccountActivity (1).xls
4    9451.53      29  AccountActivity (1).xls

                                       __source_path __source_ext  \
0  C:\Users\shai\Documents\personal\personal_proj...         .xls
1  C:\Users\shai\Documents\personal\personal_proj...         .xls
2  C:\Users\shai\Documents\personal\personal_proj...         .xls
3  C:\Users\shai\Documents\personal\personal_proj...         .xls
4  C:\Users\shai\Documents\personal\personal_proj...         .xls

                __source_rule
0  mizrachi_read_html_table_1
1  mizrachi_read_html_table_1
2  mizrachi_read_html_table_1
3  mizrachi_read_html_table_1
4  mizrachi_read_html_table_1
Requested date range: 01/01/2026 -> 01/03/2026

In [5]:
df_pending

,0,1,2,3,4,5,6,__source_file,__source_path,__source_ext,__source_rule
0,יתרה בחשבון:,29856.69,לתאריך -,05/03/26 23:15,NaN,NaN,NaN,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
1,מסגרת אשראי:,20000.00,NaN,NaN,NaN,NaN,NaN,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
2,תנועות אחרונות,NaN,NaN,NaN,NaN,NaN,NaN,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
3,תאריך,תאריך ערך,סוג תנועה,זכות,חובה,"יתרה בש""ח",אסמכתא,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
4,10/12/25,NaN,ביצוע הוראת קבע (י),NaN,600.00,9451.53,29,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
5,10/12/25,NaN,הרשאה ישראכרט (י),NaN,2874.04,NaN,20543,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
6,10/12/25,NaN,"מור גמל ופנסיה בע""מ(י)",NaN,1000.00,5577.49,57318,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
7,11/12/25,NaN,טן חברה לדלק (י),NaN,481.84,5095.65,27839,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
8,15/12/25,NaN,הרשאה מקס איט פיננס(י),NaN,7868.72,-2773.07,34685,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
9,16/12/25,NaN,זיכוי - בנק הפועלים(י),3000.00,NaN,226.93,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
10,21/12/25,NaN,ב. לאומי- קיצבת ילד(י),112.00,NaN,338.93,13104,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
11,01/01/26,NaN,"ריבית עו""ש",13.72,NaN,352.65,55555555,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
12,04/01/26,NaN,זיכוי - בנק הפועלים(י),3200.00,NaN,NaN,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
13,04/01/26,NaN,זיכוי - בנק הפועלים(י),5000.00,NaN,8552.65,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
14,11/01/26,NaN,ביצוע הוראת קבע (י),NaN,600.00,NaN,29,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
15,11/01/26,NaN,הרשאה ישראכרט (י),NaN,2504.63,NaN,20543,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
16,11/01/26,NaN,טן חברה לדלק (י),NaN,476.61,NaN,27839,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
17,11/01/26,NaN,"מור גמל ופנסיה בע""מ(י)",NaN,800.00,4171.41,57318,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
18,12/01/26,NaN,זיכוי - בנק הפועלים(י),4990.00,NaN,9161.41,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
19,15/01/26,NaN,הרשאה מקס איט פיננס(י),NaN,5875.55,3285.86,34685,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
20,20/01/26,NaN,ב. לאומי- קיצבת ילד(י),115.00,NaN,3400.86,13104,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
21,01/02/26,NaN,זיכוי - בנק הפועלים(י),5000.00,NaN,8400.86,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
22,04/02/26,NaN,זיכוי - בנק הפועלים(י),5000.00,NaN,13400.86,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
23,06/02/26,NaN,הרשאה מקס איט פיננס(י),NaN,62.78,13338.08,34685,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
24,08/02/26,NaN,זיכוי - בנק הפועלים(י),17000.00,NaN,30338.08,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
25,10/02/26,NaN,ביטוח לאומי חד פעמי(י),20315.00,NaN,NaN,63051,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
26,10/02/26,NaN,ביצוע הוראת קבע (י),NaN,600.00,NaN,29,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
27,10/02/26,NaN,הרשאה ישראכרט (י),NaN,3427.00,NaN,20543,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
28,10/02/26,NaN,הרשאה מקס איט פיננס(י),NaN,500.00,NaN,34685,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
29,10/02/26,NaN,"מור גמל ופנסיה בע""מ(י)",NaN,800.00,45326.08,57318,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
30,13/02/26,NaN,ביטוח לאומי חד פעמי(י),946.00,NaN,NaN,63051,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
31,13/02/26,NaN,העברה באינטרנט (י),NaN,2000.00,44272.08,6715,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
32,15/02/26,NaN,הרשאה מקס איט פיננס(י),NaN,12989.39,NaN,34685,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
33,15/02/26,NaN,העברה באינטרנט (י),NaN,1400.00,29882.69,25643,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
34,20/02/26,NaN,ב. לאומי- קיצבת ילד(י),115.00,NaN,29997.69,13104,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
35,25/02/26,NaN,ביטוח לאומי חד פעמי(י),219.00,NaN,30216.69,63051,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
36,תנועות היום,NaN,NaN,NaN,NaN,NaN,NaN,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
37,תנועות היום הן תנועות בחשבון שבוצעו ביום העסקי...,NaN,NaN,NaN,NaN,NaN,NaN,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1

In [6]:
    columns_numbers = range(len(df_pending.columns))
    for column_number in columns_numbers:
        temp_column = df_pending.columns[column_number]
        first_row_detected = 3 # default to 3 rows in this case
        if df_pending.iloc[0, temp_column].isna():
            print(f"Header row detected in column {column_number}")
            first_row_detected = df_pending[temp_column].isna().sum()
            break

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types

In [7]:
columns_numbers = range(len(df_pending.columns))

In [8]:
columns_numbers

range(0, 11)

In [9]:
column_number = 4

In [10]:
temp_column = df_pending.columns[column_number]

In [11]:
temp_column

'4'

In [12]:
df_pending.iloc[0, temp_column].isna()

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types

In [13]:
df_pending.iloc[0, column_number]

nan

In [14]:
df_pending.iloc[0, column_number].isna()

AttributeError: 'float' object has no attribute 'isna'

In [15]:
df_pending.iloc[0, column_number]

nan

In [16]:
df_pending.iloc[0, column_number].isna()

AttributeError: 'float' object has no attribute 'isna'

In [17]:
df_pending.iloc[0, column_number].isnull()

AttributeError: 'float' object has no attribute 'isnull'

In [18]:
import pandas as pd

In [19]:
pd.isnull(df_pending.iloc[0, column_number])

True

In [20]:
df_pending[temp_column].isna()

0      True
1      True
2      True
3     False
4     False
5     False
6     False
7     False
8     False
9      True
10     True
11     True
12     True
13     True
14    False
15    False
16    False
17    False
18     True
19    False
20     True
21     True
22     True
23    False
24     True
25     True
26    False
27    False
28    False
29    False
30     True
31    False
32    False
33    False
34     True
35     True
36     True
37     True
Name: 4, dtype: bool

In [21]:
df_pending[temp_column].isna().sum()

np.int64(19)

In [22]:
df_pending[temp_column].notna()

0     False
1     False
2     False
3      True
4      True
5      True
6      True
7      True
8      True
9     False
10    False
11    False
12    False
13    False
14     True
15     True
16     True
17     True
18    False
19     True
20    False
21    False
22    False
23     True
24    False
25    False
26     True
27     True
28     True
29     True
30    False
31     True
32     True
33     True
34    False
35    False
36    False
37    False
Name: 4, dtype: bool

In [23]:
df_pending[temp_column].notna().head(0)

Series([], Name: 4, dtype: bool)

In [24]:
df_pending[temp_column].notna().head(1)

0    False
Name: 4, dtype: bool

In [25]:
df_pending[temp_column].notna().head(0).env.index

AttributeError: 'Series' object has no attribute 'env'

In [26]:
df_pending[temp_column].notna().head(0).index

RangeIndex(start=0, stop=0, step=1)

In [27]:
df_pending[temp_column].notna()

0     False
1     False
2     False
3      True
4      True
5      True
6      True
7      True
8      True
9     False
10    False
11    False
12    False
13    False
14     True
15     True
16     True
17     True
18    False
19     True
20    False
21    False
22    False
23     True
24    False
25    False
26     True
27     True
28     True
29     True
30    False
31     True
32     True
33     True
34    False
35    False
36    False
37    False
Name: 4, dtype: bool

In [28]:
df_pending[temp_column].notna()[df_pending[temp_column].notna()]

3     True
4     True
5     True
6     True
7     True
8     True
14    True
15    True
16    True
17    True
19    True
23    True
26    True
27    True
28    True
29    True
31    True
32    True
33    True
Name: 4, dtype: bool

In [29]:
df_pending[temp_column].notna()[df_pending[temp_column].notna()].index

Index([3, 4, 5, 6, 7, 8, 14, 15, 16, 17, 19, 23, 26, 27, 28, 29, 31, 32, 33], dtype='int64')

In [30]:
df_pending[temp_column].notna()[df_pending[temp_column].notna()].index[0]

np.int64(3)

In [31]:
df = df_pending

In [32]:
df

,0,1,2,3,4,5,6,__source_file,__source_path,__source_ext,__source_rule
0,יתרה בחשבון:,29856.69,לתאריך -,05/03/26 23:15,NaN,NaN,NaN,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
1,מסגרת אשראי:,20000.00,NaN,NaN,NaN,NaN,NaN,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
2,תנועות אחרונות,NaN,NaN,NaN,NaN,NaN,NaN,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
3,תאריך,תאריך ערך,סוג תנועה,זכות,חובה,"יתרה בש""ח",אסמכתא,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
4,10/12/25,NaN,ביצוע הוראת קבע (י),NaN,600.00,9451.53,29,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
5,10/12/25,NaN,הרשאה ישראכרט (י),NaN,2874.04,NaN,20543,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
6,10/12/25,NaN,"מור גמל ופנסיה בע""מ(י)",NaN,1000.00,5577.49,57318,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
7,11/12/25,NaN,טן חברה לדלק (י),NaN,481.84,5095.65,27839,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
8,15/12/25,NaN,הרשאה מקס איט פיננס(י),NaN,7868.72,-2773.07,34685,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
9,16/12/25,NaN,זיכוי - בנק הפועלים(י),3000.00,NaN,226.93,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
10,21/12/25,NaN,ב. לאומי- קיצבת ילד(י),112.00,NaN,338.93,13104,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
11,01/01/26,NaN,"ריבית עו""ש",13.72,NaN,352.65,55555555,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
12,04/01/26,NaN,זיכוי - בנק הפועלים(י),3200.00,NaN,NaN,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
13,04/01/26,NaN,זיכוי - בנק הפועלים(י),5000.00,NaN,8552.65,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
14,11/01/26,NaN,ביצוע הוראת קבע (י),NaN,600.00,NaN,29,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
15,11/01/26,NaN,הרשאה ישראכרט (י),NaN,2504.63,NaN,20543,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
16,11/01/26,NaN,טן חברה לדלק (י),NaN,476.61,NaN,27839,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
17,11/01/26,NaN,"מור גמל ופנסיה בע""מ(י)",NaN,800.00,4171.41,57318,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
18,12/01/26,NaN,זיכוי - בנק הפועלים(י),4990.00,NaN,9161.41,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
19,15/01/26,NaN,הרשאה מקס איט פיננס(י),NaN,5875.55,3285.86,34685,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
20,20/01/26,NaN,ב. לאומי- קיצבת ילד(י),115.00,NaN,3400.86,13104,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
21,01/02/26,NaN,זיכוי - בנק הפועלים(י),5000.00,NaN,8400.86,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
22,04/02/26,NaN,זיכוי - בנק הפועלים(י),5000.00,NaN,13400.86,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
23,06/02/26,NaN,הרשאה מקס איט פיננס(י),NaN,62.78,13338.08,34685,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
24,08/02/26,NaN,זיכוי - בנק הפועלים(י),17000.00,NaN,30338.08,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
25,10/02/26,NaN,ביטוח לאומי חד פעמי(י),20315.00,NaN,NaN,63051,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
26,10/02/26,NaN,ביצוע הוראת קבע (י),NaN,600.00,NaN,29,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
27,10/02/26,NaN,הרשאה ישראכרט (י),NaN,3427.00,NaN,20543,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
28,10/02/26,NaN,הרשאה מקס איט פיננס(י),NaN,500.00,NaN,34685,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
29,10/02/26,NaN,"מור גמל ופנסיה בע""מ(י)",NaN,800.00,45326.08,57318,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
30,13/02/26,NaN,ביטוח לאומי חד פעמי(י),946.00,NaN,NaN,63051,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
31,13/02/26,NaN,העברה באינטרנט (י),NaN,2000.00,44272.08,6715,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
32,15/02/26,NaN,הרשאה מקס איט פיננס(י),NaN,12989.39,NaN,34685,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
33,15/02/26,NaN,העברה באינטרנט (י),NaN,1400.00,29882.69,25643,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
34,20/02/26,NaN,ב. לאומי- קיצבת ילד(י),115.00,NaN,29997.69,13104,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
35,25/02/26,NaN,ביטוח לאומי חד פעמי(י),219.00,NaN,30216.69,63051,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
36,תנועות היום,NaN,NaN,NaN,NaN,NaN,NaN,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
37,תנועות היום הן תנועות בחשבון שבוצעו ביום העסקי...,NaN,NaN,NaN,NaN,NaN,NaN,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1

In [33]:
df[2]

KeyError: 2

In [34]:
df['2']

0                   לתאריך -
1                        NaN
2                        NaN
3                  סוג תנועה
4        ביצוע הוראת קבע (י)
5          הרשאה ישראכרט (י)
6     מור גמל ופנסיה בע"מ(י)
7           טן חברה לדלק (י)
8     הרשאה מקס איט פיננס(י)
9     זיכוי - בנק הפועלים(י)
10    ב. לאומי- קיצבת ילד(י)
11                ריבית עו"ש
12    זיכוי - בנק הפועלים(י)
13    זיכוי - בנק הפועלים(י)
14       ביצוע הוראת קבע (י)
15         הרשאה ישראכרט (י)
16          טן חברה לדלק (י)
17    מור גמל ופנסיה בע"מ(י)
18    זיכוי - בנק הפועלים(י)
19    הרשאה מקס איט פיננס(י)
20    ב. לאומי- קיצבת ילד(י)
21    זיכוי - בנק הפועלים(י)
22    זיכוי - בנק הפועלים(י)
23    הרשאה מקס איט פיננס(י)
24    זיכוי - בנק הפועלים(י)
25    ביטוח לאומי חד פעמי(י)
26       ביצוע הוראת קבע (י)
27         הרשאה ישראכרט (י)
28    הרשאה מקס איט פיננס(י)
29    מור גמל ופנסיה בע"מ(י)
30    ביטוח לאומי חד פעמי(י)
31        העברה באינטרנט (י)
32    הרשאה מקס איט פיננס(י)
33        העברה באינטרנט (י)
34    ב. לאומי- קיצבת ילד(י)
35    ביטוח לאומי חד פעמי(י)
36                       NaN
37                       NaN
Name: 2, dtype: object

In [35]:
df['2'].iloc[0:1]

0    לתאריך -
Name: 2, dtype: object

In [36]:
df['3'].iloc[0:1]

0    05/03/26 23:15
Name: 3, dtype: object

In [37]:
df['4'].iloc[0:1]

0    NaN
Name: 4, dtype: object

In [38]:
df['4'].iloc[0:1].isna()

0    True
Name: 4, dtype: bool

In [39]:
df['4'].iloc[0:1].isna().any()

np.True_

In [40]:
probe_rows: int = 1

In [41]:
candidate_cols = [
    col for col in df.columns
    if df[col].iloc[:probe_rows].isna().any()
]

In [42]:
candidate_cols

['4', '5', '6']

In [43]:
df[candidate_cols]

           4          5         6
0        NaN        NaN       NaN
1        NaN        NaN       NaN
2        NaN        NaN       NaN
3       חובה  יתרה בש"ח    אסמכתא
4     600.00    9451.53        29
5    2874.04        NaN     20543
6    1000.00    5577.49     57318
7     481.84    5095.65     27839
8    7868.72   -2773.07     34685
9        NaN     226.93     99012
10       NaN     338.93     13104
11       NaN     352.65  55555555
12       NaN        NaN     99012
13       NaN    8552.65     99012
14    600.00        NaN        29
15   2504.63        NaN     20543
16    476.61        NaN     27839
17    800.00    4171.41     57318
18       NaN    9161.41     99012
19   5875.55    3285.86     34685
20       NaN    3400.86     13104
21       NaN    8400.86     99012
22       NaN   13400.86     99012
23     62.78   13338.08     34685
24       NaN   30338.08     99012
25       NaN        NaN     63051
26    600.00        NaN        29
27   3427.00        NaN     20543
28    500.00        NaN     34685
29    800.00   45326.08     57318
30       NaN        NaN     63051
31   2000.00   44272.08      6715
32  12989.39        NaN     34685
33   1400.00   29882.69     25643
34       NaN   29997.69     13104
35       NaN   30216.69     63051
36       NaN        NaN       NaN
37       NaN        NaN       NaN

In [44]:
df[candidate_cols[0]]

0          NaN
1          NaN
2          NaN
3         חובה
4       600.00
5      2874.04
6      1000.00
7       481.84
8      7868.72
9          NaN
10         NaN
11         NaN
12         NaN
13         NaN
14      600.00
15     2504.63
16      476.61
17      800.00
18         NaN
19     5875.55
20         NaN
21         NaN
22         NaN
23       62.78
24         NaN
25         NaN
26      600.00
27     3427.00
28      500.00
29      800.00
30         NaN
31     2000.00
32    12989.39
33     1400.00
34         NaN
35         NaN
36         NaN
37         NaN
Name: 4, dtype: object

In [45]:
df[candidate_cols[0]].find_valid_index()

AttributeError: 'Series' object has no attribute 'find_valid_index'

In [46]:
df[candidate_cols[0]].first_valid_index()

3

In [47]:
from etl_sources.mizrachi_reader import load_mizrachi_tables
import pandas as pd


def detect_header_row_mizrachi_case(
    df: pd.DataFrame,
    default_row: int = 3,
    probe_rows: int = 1,
) -> int:
    """
    Heuristic:
    1) Find first column that has NaN in the first `probe_rows`.
    2) In that column, return first non-null row index.
    3) If no signal found, return default_row.
    """
    if df.empty:
        return default_row
    # Step 1: columns that look like your Mizrachi signature
    candidate_cols = [
        col for col in df.columns
        if df[col].iloc[:probe_rows].isna().any()
    ]
    # Step 2: find first non-null row in first matching column
    for col in candidate_cols:
        first_valid = df[col].first_valid_index()  # returns None if all null
        if first_valid is not None:
            return int(first_valid)
    return default_row

In [48]:
loaded_tables = load_mizrachi_tables(folder=path_to_folder, recursive=False)
print(f"Loaded files: {len(loaded_tables)}")

for table in loaded_tables:
    print(f"\nFile: {table.path.name} ({table.extension})")
    df_pending = table.dataframe
    print(df_pending.head())

if dates_range:
    print(f"Requested date range: {dates_range[0]} -> {dates_range[1]}")


# Header row detection
# I want to detect a column that it's first row is NAN, that is a good enough signautre to detect header row.
first_row_detected = detect_header_row_mizrachi_case(df_pending)

Loaded files: 1

File: AccountActivity (1).xls (.xls)
                0          1                    2               3       4  \
0    יתרה בחשבון:   29856.69             לתאריך -  05/03/26 23:15     NaN
1    מסגרת אשראי:   20000.00                  NaN             NaN     NaN
2  תנועות אחרונות        NaN                  NaN             NaN     NaN
3           תאריך  תאריך ערך            סוג תנועה            זכות    חובה
4        10/12/25        NaN  ביצוע הוראת קבע (י)             NaN  600.00

           5       6            __source_file  \
0        NaN     NaN  AccountActivity (1).xls
1        NaN     NaN  AccountActivity (1).xls
2        NaN     NaN  AccountActivity (1).xls
3  יתרה בש"ח  אסמכתא  AccountActivity (1).xls
4    9451.53      29  AccountActivity (1).xls

                                       __source_path __source_ext  \
0  C:\Users\shai\Documents\personal\personal_proj...         .xls
1  C:\Users\shai\Documents\personal\personal_proj...         .xls
2  C:\Users\shai\Documents\personal\personal_proj...         .xls
3  C:\Users\shai\Documents\personal\personal_proj...         .xls
4  C:\Users\shai\Documents\personal\personal_proj...         .xls

                __source_rule
0  mizrachi_read_html_table_1
1  mizrachi_read_html_table_1
2  mizrachi_read_html_table_1
3  mizrachi_read_html_table_1
4  mizrachi_read_html_table_1
Requested date range: 01/01/2026 -> 01/03/2026

In [49]:
first_row_detected

3

In [50]:
df_pending = df_pending.iloc[first_row_detected:]

In [51]:
df_pending

,0,1,2,3,4,5,6,__source_file,__source_path,__source_ext,__source_rule
3,תאריך,תאריך ערך,סוג תנועה,זכות,חובה,"יתרה בש""ח",אסמכתא,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
4,10/12/25,NaN,ביצוע הוראת קבע (י),NaN,600.00,9451.53,29,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
5,10/12/25,NaN,הרשאה ישראכרט (י),NaN,2874.04,NaN,20543,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
6,10/12/25,NaN,"מור גמל ופנסיה בע""מ(י)",NaN,1000.00,5577.49,57318,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
7,11/12/25,NaN,טן חברה לדלק (י),NaN,481.84,5095.65,27839,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
8,15/12/25,NaN,הרשאה מקס איט פיננס(י),NaN,7868.72,-2773.07,34685,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
9,16/12/25,NaN,זיכוי - בנק הפועלים(י),3000.00,NaN,226.93,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
10,21/12/25,NaN,ב. לאומי- קיצבת ילד(י),112.00,NaN,338.93,13104,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
11,01/01/26,NaN,"ריבית עו""ש",13.72,NaN,352.65,55555555,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
12,04/01/26,NaN,זיכוי - בנק הפועלים(י),3200.00,NaN,NaN,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
13,04/01/26,NaN,זיכוי - בנק הפועלים(י),5000.00,NaN,8552.65,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
14,11/01/26,NaN,ביצוע הוראת קבע (י),NaN,600.00,NaN,29,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
15,11/01/26,NaN,הרשאה ישראכרט (י),NaN,2504.63,NaN,20543,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
16,11/01/26,NaN,טן חברה לדלק (י),NaN,476.61,NaN,27839,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
17,11/01/26,NaN,"מור גמל ופנסיה בע""מ(י)",NaN,800.00,4171.41,57318,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
18,12/01/26,NaN,זיכוי - בנק הפועלים(י),4990.00,NaN,9161.41,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
19,15/01/26,NaN,הרשאה מקס איט פיננס(י),NaN,5875.55,3285.86,34685,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
20,20/01/26,NaN,ב. לאומי- קיצבת ילד(י),115.00,NaN,3400.86,13104,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
21,01/02/26,NaN,זיכוי - בנק הפועלים(י),5000.00,NaN,8400.86,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
22,04/02/26,NaN,זיכוי - בנק הפועלים(י),5000.00,NaN,13400.86,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
23,06/02/26,NaN,הרשאה מקס איט פיננס(י),NaN,62.78,13338.08,34685,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
24,08/02/26,NaN,זיכוי - בנק הפועלים(י),17000.00,NaN,30338.08,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
25,10/02/26,NaN,ביטוח לאומי חד פעמי(י),20315.00,NaN,NaN,63051,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
26,10/02/26,NaN,ביצוע הוראת קבע (י),NaN,600.00,NaN,29,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
27,10/02/26,NaN,הרשאה ישראכרט (י),NaN,3427.00,NaN,20543,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
28,10/02/26,NaN,הרשאה מקס איט פיננס(י),NaN,500.00,NaN,34685,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
29,10/02/26,NaN,"מור גמל ופנסיה בע""מ(י)",NaN,800.00,45326.08,57318,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
30,13/02/26,NaN,ביטוח לאומי חד פעמי(י),946.00,NaN,NaN,63051,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
31,13/02/26,NaN,העברה באינטרנט (י),NaN,2000.00,44272.08,6715,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
32,15/02/26,NaN,הרשאה מקס איט פיננס(י),NaN,12989.39,NaN,34685,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
33,15/02/26,NaN,העברה באינטרנט (י),NaN,1400.00,29882.69,25643,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
34,20/02/26,NaN,ב. לאומי- קיצבת ילד(י),115.00,NaN,29997.69,13104,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
35,25/02/26,NaN,ביטוח לאומי חד פעמי(י),219.00,NaN,30216.69,63051,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
36,תנועות היום,NaN,NaN,NaN,NaN,NaN,NaN,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
37,תנועות היום הן תנועות בחשבון שבוצעו ביום העסקי...,NaN,NaN,NaN,NaN,NaN,NaN,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1

In [52]:
df

,0,1,2,3,4,5,6,__source_file,__source_path,__source_ext,__source_rule
0,יתרה בחשבון:,29856.69,לתאריך -,05/03/26 23:15,NaN,NaN,NaN,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
1,מסגרת אשראי:,20000.00,NaN,NaN,NaN,NaN,NaN,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
2,תנועות אחרונות,NaN,NaN,NaN,NaN,NaN,NaN,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
3,תאריך,תאריך ערך,סוג תנועה,זכות,חובה,"יתרה בש""ח",אסמכתא,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
4,10/12/25,NaN,ביצוע הוראת קבע (י),NaN,600.00,9451.53,29,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
5,10/12/25,NaN,הרשאה ישראכרט (י),NaN,2874.04,NaN,20543,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
6,10/12/25,NaN,"מור גמל ופנסיה בע""מ(י)",NaN,1000.00,5577.49,57318,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
7,11/12/25,NaN,טן חברה לדלק (י),NaN,481.84,5095.65,27839,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
8,15/12/25,NaN,הרשאה מקס איט פיננס(י),NaN,7868.72,-2773.07,34685,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
9,16/12/25,NaN,זיכוי - בנק הפועלים(י),3000.00,NaN,226.93,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
10,21/12/25,NaN,ב. לאומי- קיצבת ילד(י),112.00,NaN,338.93,13104,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
11,01/01/26,NaN,"ריבית עו""ש",13.72,NaN,352.65,55555555,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
12,04/01/26,NaN,זיכוי - בנק הפועלים(י),3200.00,NaN,NaN,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
13,04/01/26,NaN,זיכוי - בנק הפועלים(י),5000.00,NaN,8552.65,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
14,11/01/26,NaN,ביצוע הוראת קבע (י),NaN,600.00,NaN,29,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
15,11/01/26,NaN,הרשאה ישראכרט (י),NaN,2504.63,NaN,20543,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
16,11/01/26,NaN,טן חברה לדלק (י),NaN,476.61,NaN,27839,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
17,11/01/26,NaN,"מור גמל ופנסיה בע""מ(י)",NaN,800.00,4171.41,57318,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
18,12/01/26,NaN,זיכוי - בנק הפועלים(י),4990.00,NaN,9161.41,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
19,15/01/26,NaN,הרשאה מקס איט פיננס(י),NaN,5875.55,3285.86,34685,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
20,20/01/26,NaN,ב. לאומי- קיצבת ילד(י),115.00,NaN,3400.86,13104,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
21,01/02/26,NaN,זיכוי - בנק הפועלים(י),5000.00,NaN,8400.86,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
22,04/02/26,NaN,זיכוי - בנק הפועלים(י),5000.00,NaN,13400.86,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
23,06/02/26,NaN,הרשאה מקס איט פיננס(י),NaN,62.78,13338.08,34685,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
24,08/02/26,NaN,זיכוי - בנק הפועלים(י),17000.00,NaN,30338.08,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
25,10/02/26,NaN,ביטוח לאומי חד פעמי(י),20315.00,NaN,NaN,63051,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
26,10/02/26,NaN,ביצוע הוראת קבע (י),NaN,600.00,NaN,29,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
27,10/02/26,NaN,הרשאה ישראכרט (י),NaN,3427.00,NaN,20543,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
28,10/02/26,NaN,הרשאה מקס איט פיננס(י),NaN,500.00,NaN,34685,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
29,10/02/26,NaN,"מור גמל ופנסיה בע""מ(י)",NaN,800.00,45326.08,57318,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
30,13/02/26,NaN,ביטוח לאומי חד פעמי(י),946.00,NaN,NaN,63051,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
31,13/02/26,NaN,העברה באינטרנט (י),NaN,2000.00,44272.08,6715,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
32,15/02/26,NaN,הרשאה מקס איט פיננס(י),NaN,12989.39,NaN,34685,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
33,15/02/26,NaN,העברה באינטרנט (י),NaN,1400.00,29882.69,25643,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
34,20/02/26,NaN,ב. לאומי- קיצבת ילד(י),115.00,NaN,29997.69,13104,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
35,25/02/26,NaN,ביטוח לאומי חד פעמי(י),219.00,NaN,30216.69,63051,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
36,תנועות היום,NaN,NaN,NaN,NaN,NaN,NaN,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
37,תנועות היום הן תנועות בחשבון שבוצעו ביום העסקי...,NaN,NaN,NaN,NaN,NaN,NaN,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1

In [53]:
df['3']

0     05/03/26 23:15
1                NaN
2                NaN
3               זכות
4                NaN
5                NaN
6                NaN
7                NaN
8                NaN
9            3000.00
10            112.00
11             13.72
12           3200.00
13           5000.00
14               NaN
15               NaN
16               NaN
17               NaN
18           4990.00
19               NaN
20            115.00
21           5000.00
22           5000.00
23               NaN
24          17000.00
25          20315.00
26               NaN
27               NaN
28               NaN
29               NaN
30            946.00
31               NaN
32               NaN
33               NaN
34            115.00
35            219.00
36               NaN
37               NaN
Name: 3, dtype: object

In [54]:
df['4']

0          NaN
1          NaN
2          NaN
3         חובה
4       600.00
5      2874.04
6      1000.00
7       481.84
8      7868.72
9          NaN
10         NaN
11         NaN
12         NaN
13         NaN
14      600.00
15     2504.63
16      476.61
17      800.00
18         NaN
19     5875.55
20         NaN
21         NaN
22         NaN
23       62.78
24         NaN
25         NaN
26      600.00
27     3427.00
28      500.00
29      800.00
30         NaN
31     2000.00
32    12989.39
33     1400.00
34         NaN
35         NaN
36         NaN
37         NaN
Name: 4, dtype: object

In [55]:
df['4'].first_valid_index()

3

In [56]:
df.loc[3:]

,0,1,2,3,4,5,6,__source_file,__source_path,__source_ext,__source_rule
3,תאריך,תאריך ערך,סוג תנועה,זכות,חובה,"יתרה בש""ח",אסמכתא,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
4,10/12/25,NaN,ביצוע הוראת קבע (י),NaN,600.00,9451.53,29,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
5,10/12/25,NaN,הרשאה ישראכרט (י),NaN,2874.04,NaN,20543,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
6,10/12/25,NaN,"מור גמל ופנסיה בע""מ(י)",NaN,1000.00,5577.49,57318,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
7,11/12/25,NaN,טן חברה לדלק (י),NaN,481.84,5095.65,27839,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
8,15/12/25,NaN,הרשאה מקס איט פיננס(י),NaN,7868.72,-2773.07,34685,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
9,16/12/25,NaN,זיכוי - בנק הפועלים(י),3000.00,NaN,226.93,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
10,21/12/25,NaN,ב. לאומי- קיצבת ילד(י),112.00,NaN,338.93,13104,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
11,01/01/26,NaN,"ריבית עו""ש",13.72,NaN,352.65,55555555,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
12,04/01/26,NaN,זיכוי - בנק הפועלים(י),3200.00,NaN,NaN,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
13,04/01/26,NaN,זיכוי - בנק הפועלים(י),5000.00,NaN,8552.65,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
14,11/01/26,NaN,ביצוע הוראת קבע (י),NaN,600.00,NaN,29,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
15,11/01/26,NaN,הרשאה ישראכרט (י),NaN,2504.63,NaN,20543,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
16,11/01/26,NaN,טן חברה לדלק (י),NaN,476.61,NaN,27839,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
17,11/01/26,NaN,"מור גמל ופנסיה בע""מ(י)",NaN,800.00,4171.41,57318,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
18,12/01/26,NaN,זיכוי - בנק הפועלים(י),4990.00,NaN,9161.41,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
19,15/01/26,NaN,הרשאה מקס איט פיננס(י),NaN,5875.55,3285.86,34685,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
20,20/01/26,NaN,ב. לאומי- קיצבת ילד(י),115.00,NaN,3400.86,13104,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
21,01/02/26,NaN,זיכוי - בנק הפועלים(י),5000.00,NaN,8400.86,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
22,04/02/26,NaN,זיכוי - בנק הפועלים(י),5000.00,NaN,13400.86,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
23,06/02/26,NaN,הרשאה מקס איט פיננס(י),NaN,62.78,13338.08,34685,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
24,08/02/26,NaN,זיכוי - בנק הפועלים(י),17000.00,NaN,30338.08,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
25,10/02/26,NaN,ביטוח לאומי חד פעמי(י),20315.00,NaN,NaN,63051,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
26,10/02/26,NaN,ביצוע הוראת קבע (י),NaN,600.00,NaN,29,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
27,10/02/26,NaN,הרשאה ישראכרט (י),NaN,3427.00,NaN,20543,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
28,10/02/26,NaN,הרשאה מקס איט פיננס(י),NaN,500.00,NaN,34685,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
29,10/02/26,NaN,"מור גמל ופנסיה בע""מ(י)",NaN,800.00,45326.08,57318,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
30,13/02/26,NaN,ביטוח לאומי חד פעמי(י),946.00,NaN,NaN,63051,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
31,13/02/26,NaN,העברה באינטרנט (י),NaN,2000.00,44272.08,6715,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
32,15/02/26,NaN,הרשאה מקס איט פיננס(י),NaN,12989.39,NaN,34685,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
33,15/02/26,NaN,העברה באינטרנט (י),NaN,1400.00,29882.69,25643,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
34,20/02/26,NaN,ב. לאומי- קיצבת ילד(י),115.00,NaN,29997.69,13104,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
35,25/02/26,NaN,ביטוח לאומי חד פעמי(י),219.00,NaN,30216.69,63051,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
36,תנועות היום,NaN,NaN,NaN,NaN,NaN,NaN,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
37,תנועות היום הן תנועות בחשבון שבוצעו ביום העסקי...,NaN,NaN,NaN,NaN,NaN,NaN,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1

In [57]:
df.loc[4:]

,0,1,2,3,4,5,6,__source_file,__source_path,__source_ext,__source_rule
4,10/12/25,NaN,ביצוע הוראת קבע (י),NaN,600.00,9451.53,29,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
5,10/12/25,NaN,הרשאה ישראכרט (י),NaN,2874.04,NaN,20543,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
6,10/12/25,NaN,"מור גמל ופנסיה בע""מ(י)",NaN,1000.00,5577.49,57318,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
7,11/12/25,NaN,טן חברה לדלק (י),NaN,481.84,5095.65,27839,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
8,15/12/25,NaN,הרשאה מקס איט פיננס(י),NaN,7868.72,-2773.07,34685,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
9,16/12/25,NaN,זיכוי - בנק הפועלים(י),3000.00,NaN,226.93,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
10,21/12/25,NaN,ב. לאומי- קיצבת ילד(י),112.00,NaN,338.93,13104,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
11,01/01/26,NaN,"ריבית עו""ש",13.72,NaN,352.65,55555555,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
12,04/01/26,NaN,זיכוי - בנק הפועלים(י),3200.00,NaN,NaN,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
13,04/01/26,NaN,זיכוי - בנק הפועלים(י),5000.00,NaN,8552.65,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
14,11/01/26,NaN,ביצוע הוראת קבע (י),NaN,600.00,NaN,29,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
15,11/01/26,NaN,הרשאה ישראכרט (י),NaN,2504.63,NaN,20543,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
16,11/01/26,NaN,טן חברה לדלק (י),NaN,476.61,NaN,27839,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
17,11/01/26,NaN,"מור גמל ופנסיה בע""מ(י)",NaN,800.00,4171.41,57318,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
18,12/01/26,NaN,זיכוי - בנק הפועלים(י),4990.00,NaN,9161.41,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
19,15/01/26,NaN,הרשאה מקס איט פיננס(י),NaN,5875.55,3285.86,34685,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
20,20/01/26,NaN,ב. לאומי- קיצבת ילד(י),115.00,NaN,3400.86,13104,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
21,01/02/26,NaN,זיכוי - בנק הפועלים(י),5000.00,NaN,8400.86,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
22,04/02/26,NaN,זיכוי - בנק הפועלים(י),5000.00,NaN,13400.86,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
23,06/02/26,NaN,הרשאה מקס איט פיננס(י),NaN,62.78,13338.08,34685,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
24,08/02/26,NaN,זיכוי - בנק הפועלים(י),17000.00,NaN,30338.08,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
25,10/02/26,NaN,ביטוח לאומי חד פעמי(י),20315.00,NaN,NaN,63051,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
26,10/02/26,NaN,ביצוע הוראת קבע (י),NaN,600.00,NaN,29,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
27,10/02/26,NaN,הרשאה ישראכרט (י),NaN,3427.00,NaN,20543,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
28,10/02/26,NaN,הרשאה מקס איט פיננס(י),NaN,500.00,NaN,34685,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
29,10/02/26,NaN,"מור גמל ופנסיה בע""מ(י)",NaN,800.00,45326.08,57318,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
30,13/02/26,NaN,ביטוח לאומי חד פעמי(י),946.00,NaN,NaN,63051,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
31,13/02/26,NaN,העברה באינטרנט (י),NaN,2000.00,44272.08,6715,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
32,15/02/26,NaN,הרשאה מקס איט פיננס(י),NaN,12989.39,NaN,34685,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
33,15/02/26,NaN,העברה באינטרנט (י),NaN,1400.00,29882.69,25643,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
34,20/02/26,NaN,ב. לאומי- קיצבת ילד(י),115.00,NaN,29997.69,13104,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
35,25/02/26,NaN,ביטוח לאומי חד פעמי(י),219.00,NaN,30216.69,63051,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
36,תנועות היום,NaN,NaN,NaN,NaN,NaN,NaN,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
37,תנועות היום הן תנועות בחשבון שבוצעו ביום העסקי...,NaN,NaN,NaN,NaN,NaN,NaN,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1

In [58]:
df.iloc[first_row_detected:first_row_detected+1]

,0,1,2,3,4,5,6,__source_file,__source_path,__source_ext,__source_rule
3,תאריך,תאריך ערך,סוג תנועה,זכות,חובה,"יתרה בש""ח",אסמכתא,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1

In [59]:
df.iloc[first_row_detected+2:first_row_detected+2]

Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, __source_file, __source_path, __source_ext, __source_rule]
Index: []

In [60]:
df.iloc[first_row_detected:first_row_detected]

Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, __source_file, __source_path, __source_ext, __source_rule]
Index: []

In [61]:
df.iloc[first_row_detected:first_row_detected+1]

,0,1,2,3,4,5,6,__source_file,__source_path,__source_ext,__source_rule
3,תאריך,תאריך ערך,סוג תנועה,זכות,חובה,"יתרה בש""ח",אסמכתא,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1

In [62]:
df.iloc[first_row_detected:first_row_detected+1].values

array([['תאריך', 'תאריך ערך', 'סוג תנועה', 'זכות', 'חובה', 'יתרה בש"ח',
        'אסמכתא', 'AccountActivity (1).xls',
        'C:\\Users\\shai\\Documents\\personal\\personal_projects\\ynab-israel-consolidator\\private_data\\incoming\\bank_mizrachi\\AccountActivity (1).xls',
        '.xls', 'mizrachi_read_html_table_1']], dtype=object)

In [63]:
df.iloc[first_row_detected:first_row_detected+1,:]

,0,1,2,3,4,5,6,__source_file,__source_path,__source_ext,__source_rule
3,תאריך,תאריך ערך,סוג תנועה,זכות,חובה,"יתרה בש""ח",אסמכתא,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1

In [64]:
df.iloc[first_row_detected:first_row_detected+1,:].values

array([['תאריך', 'תאריך ערך', 'סוג תנועה', 'זכות', 'חובה', 'יתרה בש"ח',
        'אסמכתא', 'AccountActivity (1).xls',
        'C:\\Users\\shai\\Documents\\personal\\personal_projects\\ynab-israel-consolidator\\private_data\\incoming\\bank_mizrachi\\AccountActivity (1).xls',
        '.xls', 'mizrachi_read_html_table_1']], dtype=object)

In [65]:
df.iloc[first_row_detected:first_row_detected+1,:].values[0]

array(['תאריך', 'תאריך ערך', 'סוג תנועה', 'זכות', 'חובה', 'יתרה בש"ח',
       'אסמכתא', 'AccountActivity (1).xls',
       'C:\\Users\\shai\\Documents\\personal\\personal_projects\\ynab-israel-consolidator\\private_data\\incoming\\bank_mizrachi\\AccountActivity (1).xls',
       '.xls', 'mizrachi_read_html_table_1'], dtype=object)

In [66]:
header_row_idx = detect_header_row_mizrachi_case(df_pending)

In [67]:
df_pending.iloc[header_row_idx, :]

0                                                         10/12/25
1                                                              NaN
2                                           מור גמל ופנסיה בע"מ(י)
3                                                              NaN
4                                                          1000.00
5                                                          5577.49
6                                                            57318
__source_file                              AccountActivity (1).xls
__source_path    C:\Users\shai\Documents\personal\personal_proj...
__source_ext                                                  .xls
__source_rule                           mizrachi_read_html_table_1
Name: 6, dtype: object

In [68]:
loaded_tables = load_mizrachi_tables(folder=path_to_folder, recursive=False)
print(f"Loaded files: {len(loaded_tables)}")

for table in loaded_tables:
    print(f"\nFile: {table.path.name} ({table.extension})")
    df_pending = table.dataframe
    print(df_pending.head())

if dates_range:
    print(f"Requested date range: {dates_range[0]} -> {dates_range[1]}")


# Header row detection
# Detect header row in Mizrachi export via NaN-first-row signature.
header_row_idx = detect_header_row_mizrachi_case(df_pending)
df_pending.columns = df_pending.iloc[header_row_idx, :]

Loaded files: 1

File: AccountActivity (1).xls (.xls)
                0          1                    2               3       4  \
0    יתרה בחשבון:   29856.69             לתאריך -  05/03/26 23:15     NaN
1    מסגרת אשראי:   20000.00                  NaN             NaN     NaN
2  תנועות אחרונות        NaN                  NaN             NaN     NaN
3           תאריך  תאריך ערך            סוג תנועה            זכות    חובה
4        10/12/25        NaN  ביצוע הוראת קבע (י)             NaN  600.00

           5       6            __source_file  \
0        NaN     NaN  AccountActivity (1).xls
1        NaN     NaN  AccountActivity (1).xls
2        NaN     NaN  AccountActivity (1).xls
3  יתרה בש"ח  אסמכתא  AccountActivity (1).xls
4    9451.53      29  AccountActivity (1).xls

                                       __source_path __source_ext  \
0  C:\Users\shai\Documents\personal\personal_proj...         .xls
1  C:\Users\shai\Documents\personal\personal_proj...         .xls
2  C:\Users\shai\Documents\personal\personal_proj...         .xls
3  C:\Users\shai\Documents\personal\personal_proj...         .xls
4  C:\Users\shai\Documents\personal\personal_proj...         .xls

                __source_rule
0  mizrachi_read_html_table_1
1  mizrachi_read_html_table_1
2  mizrachi_read_html_table_1
3  mizrachi_read_html_table_1
4  mizrachi_read_html_table_1
Requested date range: 01/01/2026 -> 01/03/2026

In [69]:
df_pending.iloc[header_row_idx, :]

3
תאריך                                                                                                                                                                                  תאריך
תאריך ערך                                                                                                                                                                          תאריך ערך
סוג תנועה                                                                                                                                                                          סוג תנועה
זכות                                                                                                                                                                                    זכות
חובה                                                                                                                                                                                    חובה
יתרה בש"ח                                                                                                                                                                          יתרה בש"ח
אסמכתא                                                                                                                                                                                אסמכתא
AccountActivity (1).xls                                                                                                                                              AccountActivity (1).xls
C:\Users\shai\Documents\personal\personal_projects\ynab-israel-consolidator\private_data\incoming\bank_mizrachi\AccountActivity (1).xls    C:\Users\shai\Documents\personal\personal_proj...
.xls                                                                                                                                                                                    .xls
mizrachi_read_html_table_1                                                                                                                                        mizrachi_read_html_table_1
Name: 3, dtype: object

In [70]:
df_pending.columns

Index(['תאריך', 'תאריך ערך', 'סוג תנועה', 'זכות', 'חובה', 'יתרה בש"ח',
       'אסמכתא', 'AccountActivity (1).xls',
       'C:\Users\shai\Documents\personal\personal_projects\ynab-israel-consolidator\private_data\incoming\bank_mizrachi\AccountActivity (1).xls',
       '.xls', 'mizrachi_read_html_table_1'],
      dtype='object', name=3)

In [71]:
df_pending

3,תאריך,תאריך ערך,סוג תנועה,זכות,חובה,"יתרה בש""ח",אסמכתא,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_projects\ynab-israel-consolidator\private_data\incoming\bank_mizrachi\AccountActivity (1).xls,.xls,mizrachi_read_html_table_1
0,יתרה בחשבון:,29856.69,לתאריך -,05/03/26 23:15,NaN,NaN,NaN,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
1,מסגרת אשראי:,20000.00,NaN,NaN,NaN,NaN,NaN,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
2,תנועות אחרונות,NaN,NaN,NaN,NaN,NaN,NaN,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
3,תאריך,תאריך ערך,סוג תנועה,זכות,חובה,"יתרה בש""ח",אסמכתא,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
4,10/12/25,NaN,ביצוע הוראת קבע (י),NaN,600.00,9451.53,29,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
5,10/12/25,NaN,הרשאה ישראכרט (י),NaN,2874.04,NaN,20543,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
6,10/12/25,NaN,"מור גמל ופנסיה בע""מ(י)",NaN,1000.00,5577.49,57318,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
7,11/12/25,NaN,טן חברה לדלק (י),NaN,481.84,5095.65,27839,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
8,15/12/25,NaN,הרשאה מקס איט פיננס(י),NaN,7868.72,-2773.07,34685,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
9,16/12/25,NaN,זיכוי - בנק הפועלים(י),3000.00,NaN,226.93,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
10,21/12/25,NaN,ב. לאומי- קיצבת ילד(י),112.00,NaN,338.93,13104,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
11,01/01/26,NaN,"ריבית עו""ש",13.72,NaN,352.65,55555555,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
12,04/01/26,NaN,זיכוי - בנק הפועלים(י),3200.00,NaN,NaN,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
13,04/01/26,NaN,זיכוי - בנק הפועלים(י),5000.00,NaN,8552.65,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
14,11/01/26,NaN,ביצוע הוראת קבע (י),NaN,600.00,NaN,29,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
15,11/01/26,NaN,הרשאה ישראכרט (י),NaN,2504.63,NaN,20543,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
16,11/01/26,NaN,טן חברה לדלק (י),NaN,476.61,NaN,27839,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
17,11/01/26,NaN,"מור גמל ופנסיה בע""מ(י)",NaN,800.00,4171.41,57318,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
18,12/01/26,NaN,זיכוי - בנק הפועלים(י),4990.00,NaN,9161.41,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
19,15/01/26,NaN,הרשאה מקס איט פיננס(י),NaN,5875.55,3285.86,34685,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
20,20/01/26,NaN,ב. לאומי- קיצבת ילד(י),115.00,NaN,3400.86,13104,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
21,01/02/26,NaN,זיכוי - בנק הפועלים(י),5000.00,NaN,8400.86,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
22,04/02/26,NaN,זיכוי - בנק הפועלים(י),5000.00,NaN,13400.86,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
23,06/02/26,NaN,הרשאה מקס איט פיננס(י),NaN,62.78,13338.08,34685,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
24,08/02/26,NaN,זיכוי - בנק הפועלים(י),17000.00,NaN,30338.08,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
25,10/02/26,NaN,ביטוח לאומי חד פעמי(י),20315.00,NaN,NaN,63051,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
26,10/02/26,NaN,ביצוע הוראת קבע (י),NaN,600.00,NaN,29,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
27,10/02/26,NaN,הרשאה ישראכרט (י),NaN,3427.00,NaN,20543,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
28,10/02/26,NaN,הרשאה מקס איט פיננס(י),NaN,500.00,NaN,34685,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
29,10/02/26,NaN,"מור גמל ופנסיה בע""מ(י)",NaN,800.00,45326.08,57318,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
30,13/02/26,NaN,ביטוח לאומי חד פעמי(י),946.00,NaN,NaN,63051,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
31,13/02/26,NaN,העברה באינטרנט (י),NaN,2000.00,44272.08,6715,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
32,15/02/26,NaN,הרשאה מקס איט פיננס(י),NaN,12989.39,NaN,34685,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
33,15/02/26,NaN,העברה באינטרנט (י),NaN,1400.00,29882.69,25643,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
34,20/02/26,NaN,ב. לאומי- קיצבת ילד(י),115.00,NaN,29997.69,13104,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
35,25/02/26,NaN,ביטוח לאומי חד פעמי(י),219.00,NaN,30216.69,63051,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
36,תנועות היום,NaN,NaN,NaN,NaN,NaN,NaN,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
37,תנועות היום הן תנועות בחשבון שבוצעו ביום העסקי...,NaN,NaN,NaN,NaN,NaN,NaN,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1

In [72]:
loaded_tables = load_mizrachi_tables(folder=path_to_folder, recursive=False)
print(f"Loaded files: {len(loaded_tables)}")

for table in loaded_tables:
    print(f"\nFile: {table.path.name} ({table.extension})")
    df_pending = table.dataframe
    print(df_pending.head())

if dates_range:
    print(f"Requested date range: {dates_range[0]} -> {dates_range[1]}")


# Header row detection
# Detect header row in Mizrachi export via NaN-first-row signature.
header_row_idx = detect_header_row_mizrachi_case(df_pending)
df_pending.columns = df_pending.iloc[header_row_idx, :]
df_pending = df_pending.iloc[header_row_idx+1:]

Loaded files: 1

File: AccountActivity (1).xls (.xls)
                0          1                    2               3       4  \
0    יתרה בחשבון:   29856.69             לתאריך -  05/03/26 23:15     NaN
1    מסגרת אשראי:   20000.00                  NaN             NaN     NaN
2  תנועות אחרונות        NaN                  NaN             NaN     NaN
3           תאריך  תאריך ערך            סוג תנועה            זכות    חובה
4        10/12/25        NaN  ביצוע הוראת קבע (י)             NaN  600.00

           5       6            __source_file  \
0        NaN     NaN  AccountActivity (1).xls
1        NaN     NaN  AccountActivity (1).xls
2        NaN     NaN  AccountActivity (1).xls
3  יתרה בש"ח  אסמכתא  AccountActivity (1).xls
4    9451.53      29  AccountActivity (1).xls

                                       __source_path __source_ext  \
0  C:\Users\shai\Documents\personal\personal_proj...         .xls
1  C:\Users\shai\Documents\personal\personal_proj...         .xls
2  C:\Users\shai\Documents\personal\personal_proj...         .xls
3  C:\Users\shai\Documents\personal\personal_proj...         .xls
4  C:\Users\shai\Documents\personal\personal_proj...         .xls

                __source_rule
0  mizrachi_read_html_table_1
1  mizrachi_read_html_table_1
2  mizrachi_read_html_table_1
3  mizrachi_read_html_table_1
4  mizrachi_read_html_table_1
Requested date range: 01/01/2026 -> 01/03/2026

In [73]:
df_pending

3,תאריך,תאריך ערך,סוג תנועה,זכות,חובה,"יתרה בש""ח",אסמכתא,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_projects\ynab-israel-consolidator\private_data\incoming\bank_mizrachi\AccountActivity (1).xls,.xls,mizrachi_read_html_table_1
4,10/12/25,NaN,ביצוע הוראת קבע (י),NaN,600.00,9451.53,29,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
5,10/12/25,NaN,הרשאה ישראכרט (י),NaN,2874.04,NaN,20543,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
6,10/12/25,NaN,"מור גמל ופנסיה בע""מ(י)",NaN,1000.00,5577.49,57318,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
7,11/12/25,NaN,טן חברה לדלק (י),NaN,481.84,5095.65,27839,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
8,15/12/25,NaN,הרשאה מקס איט פיננס(י),NaN,7868.72,-2773.07,34685,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
9,16/12/25,NaN,זיכוי - בנק הפועלים(י),3000.00,NaN,226.93,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
10,21/12/25,NaN,ב. לאומי- קיצבת ילד(י),112.00,NaN,338.93,13104,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
11,01/01/26,NaN,"ריבית עו""ש",13.72,NaN,352.65,55555555,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
12,04/01/26,NaN,זיכוי - בנק הפועלים(י),3200.00,NaN,NaN,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
13,04/01/26,NaN,זיכוי - בנק הפועלים(י),5000.00,NaN,8552.65,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
14,11/01/26,NaN,ביצוע הוראת קבע (י),NaN,600.00,NaN,29,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
15,11/01/26,NaN,הרשאה ישראכרט (י),NaN,2504.63,NaN,20543,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
16,11/01/26,NaN,טן חברה לדלק (י),NaN,476.61,NaN,27839,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
17,11/01/26,NaN,"מור גמל ופנסיה בע""מ(י)",NaN,800.00,4171.41,57318,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
18,12/01/26,NaN,זיכוי - בנק הפועלים(י),4990.00,NaN,9161.41,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
19,15/01/26,NaN,הרשאה מקס איט פיננס(י),NaN,5875.55,3285.86,34685,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
20,20/01/26,NaN,ב. לאומי- קיצבת ילד(י),115.00,NaN,3400.86,13104,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
21,01/02/26,NaN,זיכוי - בנק הפועלים(י),5000.00,NaN,8400.86,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
22,04/02/26,NaN,זיכוי - בנק הפועלים(י),5000.00,NaN,13400.86,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
23,06/02/26,NaN,הרשאה מקס איט פיננס(י),NaN,62.78,13338.08,34685,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
24,08/02/26,NaN,זיכוי - בנק הפועלים(י),17000.00,NaN,30338.08,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
25,10/02/26,NaN,ביטוח לאומי חד פעמי(י),20315.00,NaN,NaN,63051,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
26,10/02/26,NaN,ביצוע הוראת קבע (י),NaN,600.00,NaN,29,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
27,10/02/26,NaN,הרשאה ישראכרט (י),NaN,3427.00,NaN,20543,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
28,10/02/26,NaN,הרשאה מקס איט פיננס(י),NaN,500.00,NaN,34685,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
29,10/02/26,NaN,"מור גמל ופנסיה בע""מ(י)",NaN,800.00,45326.08,57318,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
30,13/02/26,NaN,ביטוח לאומי חד פעמי(י),946.00,NaN,NaN,63051,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
31,13/02/26,NaN,העברה באינטרנט (י),NaN,2000.00,44272.08,6715,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
32,15/02/26,NaN,הרשאה מקס איט פיננס(י),NaN,12989.39,NaN,34685,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
33,15/02/26,NaN,העברה באינטרנט (י),NaN,1400.00,29882.69,25643,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
34,20/02/26,NaN,ב. לאומי- קיצבת ילד(י),115.00,NaN,29997.69,13104,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
35,25/02/26,NaN,ביטוח לאומי חד פעמי(י),219.00,NaN,30216.69,63051,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
36,תנועות היום,NaN,NaN,NaN,NaN,NaN,NaN,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
37,תנועות היום הן תנועות בחשבון שבוצעו ביום העסקי...,NaN,NaN,NaN,NaN,NaN,NaN,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1

In [74]:
loaded_tables = load_mizrachi_tables(folder=path_to_folder, recursive=False)
print(f"Loaded files: {len(loaded_tables)}")

for table in loaded_tables:
    print(f"\nFile: {table.path.name} ({table.extension})")
    df_pending = table.dataframe
    print(df_pending.head())

if dates_range:
    print(f"Requested date range: {dates_range[0]} -> {dates_range[1]}")

Loaded files: 1

File: AccountActivity (1).xls (.xls)
                0          1                    2               3       4  \
0    יתרה בחשבון:   29856.69             לתאריך -  05/03/26 23:15     NaN
1    מסגרת אשראי:   20000.00                  NaN             NaN     NaN
2  תנועות אחרונות        NaN                  NaN             NaN     NaN
3           תאריך  תאריך ערך            סוג תנועה            זכות    חובה
4        10/12/25        NaN  ביצוע הוראת קבע (י)             NaN  600.00

           5       6            __source_file  \
0        NaN     NaN  AccountActivity (1).xls
1        NaN     NaN  AccountActivity (1).xls
2        NaN     NaN  AccountActivity (1).xls
3  יתרה בש"ח  אסמכתא  AccountActivity (1).xls
4    9451.53      29  AccountActivity (1).xls

                                       __source_path __source_ext  \
0  C:\Users\shai\Documents\personal\personal_proj...         .xls
1  C:\Users\shai\Documents\personal\personal_proj...         .xls
2  C:\Users\shai\Documents\personal\personal_proj...         .xls
3  C:\Users\shai\Documents\personal\personal_proj...         .xls
4  C:\Users\shai\Documents\personal\personal_proj...         .xls

                __source_rule
0  mizrachi_read_html_table_1
1  mizrachi_read_html_table_1
2  mizrachi_read_html_table_1
3  mizrachi_read_html_table_1
4  mizrachi_read_html_table_1
Requested date range: 01/01/2026 -> 01/03/2026

In [75]:
# Header row detection
# Detect header row in Mizrachi export via NaN-first-row signature.
header_row_idx = detect_header_row_mizrachi_case(df_pending)
df_pending.columns = df_pending.iloc[header_row_idx, :]

In [76]:
df_pending.iloc[header_row_idx:]

3,תאריך,תאריך ערך,סוג תנועה,זכות,חובה,"יתרה בש""ח",אסמכתא,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_projects\ynab-israel-consolidator\private_data\incoming\bank_mizrachi\AccountActivity (1).xls,.xls,mizrachi_read_html_table_1
3,תאריך,תאריך ערך,סוג תנועה,זכות,חובה,"יתרה בש""ח",אסמכתא,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
4,10/12/25,NaN,ביצוע הוראת קבע (י),NaN,600.00,9451.53,29,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
5,10/12/25,NaN,הרשאה ישראכרט (י),NaN,2874.04,NaN,20543,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
6,10/12/25,NaN,"מור גמל ופנסיה בע""מ(י)",NaN,1000.00,5577.49,57318,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
7,11/12/25,NaN,טן חברה לדלק (י),NaN,481.84,5095.65,27839,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
8,15/12/25,NaN,הרשאה מקס איט פיננס(י),NaN,7868.72,-2773.07,34685,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
9,16/12/25,NaN,זיכוי - בנק הפועלים(י),3000.00,NaN,226.93,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
10,21/12/25,NaN,ב. לאומי- קיצבת ילד(י),112.00,NaN,338.93,13104,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
11,01/01/26,NaN,"ריבית עו""ש",13.72,NaN,352.65,55555555,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
12,04/01/26,NaN,זיכוי - בנק הפועלים(י),3200.00,NaN,NaN,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
13,04/01/26,NaN,זיכוי - בנק הפועלים(י),5000.00,NaN,8552.65,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
14,11/01/26,NaN,ביצוע הוראת קבע (י),NaN,600.00,NaN,29,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
15,11/01/26,NaN,הרשאה ישראכרט (י),NaN,2504.63,NaN,20543,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
16,11/01/26,NaN,טן חברה לדלק (י),NaN,476.61,NaN,27839,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
17,11/01/26,NaN,"מור גמל ופנסיה בע""מ(י)",NaN,800.00,4171.41,57318,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
18,12/01/26,NaN,זיכוי - בנק הפועלים(י),4990.00,NaN,9161.41,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
19,15/01/26,NaN,הרשאה מקס איט פיננס(י),NaN,5875.55,3285.86,34685,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
20,20/01/26,NaN,ב. לאומי- קיצבת ילד(י),115.00,NaN,3400.86,13104,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
21,01/02/26,NaN,זיכוי - בנק הפועלים(י),5000.00,NaN,8400.86,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
22,04/02/26,NaN,זיכוי - בנק הפועלים(י),5000.00,NaN,13400.86,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
23,06/02/26,NaN,הרשאה מקס איט פיננס(י),NaN,62.78,13338.08,34685,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
24,08/02/26,NaN,זיכוי - בנק הפועלים(י),17000.00,NaN,30338.08,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
25,10/02/26,NaN,ביטוח לאומי חד פעמי(י),20315.00,NaN,NaN,63051,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
26,10/02/26,NaN,ביצוע הוראת קבע (י),NaN,600.00,NaN,29,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
27,10/02/26,NaN,הרשאה ישראכרט (י),NaN,3427.00,NaN,20543,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
28,10/02/26,NaN,הרשאה מקס איט פיננס(י),NaN,500.00,NaN,34685,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
29,10/02/26,NaN,"מור גמל ופנסיה בע""מ(י)",NaN,800.00,45326.08,57318,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
30,13/02/26,NaN,ביטוח לאומי חד פעמי(י),946.00,NaN,NaN,63051,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
31,13/02/26,NaN,העברה באינטרנט (י),NaN,2000.00,44272.08,6715,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
32,15/02/26,NaN,הרשאה מקס איט פיננס(י),NaN,12989.39,NaN,34685,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
33,15/02/26,NaN,העברה באינטרנט (י),NaN,1400.00,29882.69,25643,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
34,20/02/26,NaN,ב. לאומי- קיצבת ילד(י),115.00,NaN,29997.69,13104,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
35,25/02/26,NaN,ביטוח לאומי חד פעמי(י),219.00,NaN,30216.69,63051,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
36,תנועות היום,NaN,NaN,NaN,NaN,NaN,NaN,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
37,תנועות היום הן תנועות בחשבון שבוצעו ביום העסקי...,NaN,NaN,NaN,NaN,NaN,NaN,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1

In [77]:
path_to_folder = r'C:\Users\shai\Documents\personal\personal_projects\ynab-israel-consolidator\private_data\incoming\bank_mizrachi'
dates_range = ("01/01/2026", "01/03/2026")

In [78]:
from etl_sources.mizrachi_reader import load_mizrachi_tables
import pandas as pd


def _dedupe_column_names(names: list[str]) -> list[str]:
    seen_counts: dict[str, int] = {}
    deduped: list[str] = []

    for name in names:
        count = seen_counts.get(name, 0) + 1
        seen_counts[name] = count
        deduped.append(name if count == 1 else f"{name}_{count}")

    return deduped


def apply_detected_header(df: pd.DataFrame, header_row_idx: int) -> pd.DataFrame:
    if df.empty:
        return df.copy()

    if header_row_idx < 0 or header_row_idx >= len(df):
        raise ValueError(
            f"Detected header_row_idx {header_row_idx} is out of bounds for dataframe with {len(df)} rows."
        )

    raw_header = df.iloc[header_row_idx, :]
    cleaned_header = []
    for col_idx, value in enumerate(raw_header):
        if pd.isna(value):
            cleaned_header.append(f"unnamed_{col_idx}")
            continue

        header_name = str(value).strip()
        cleaned_header.append(header_name or f"unnamed_{col_idx}")

    normalized_columns = _dedupe_column_names(cleaned_header)
    normalized_df = df.iloc[header_row_idx + 1 :].copy().reset_index(drop=True)
    normalized_df.columns = normalized_columns
    return normalized_df


def detect_header_row_mizrachi_case(
    df: pd.DataFrame,
    default_row: int = 3,
    probe_rows: int = 1,
) -> int:
    """
    Heuristic:
    1) Find first column that has NaN in the first `probe_rows`.
    2) In that column, return first non-null row index.
    3) If no signal found, return default_row.
    """
    if df.empty:
        return default_row
    # Step 1: columns that look like your Mizrachi signature
    candidate_cols = [
        col for col in df.columns
        if df[col].iloc[:probe_rows].isna().any()
    ]
    # Step 2: find first non-null row in first matching column
    for col in candidate_cols:
        first_valid = df[col].first_valid_index()  # returns None if all null
        if first_valid is not None:
            return int(first_valid)
    return default_row

def main(path_to_folder: str, dates_range: tuple[str, str] | None = None) -> None:
    loaded_tables = load_mizrachi_tables(folder=path_to_folder, recursive=False)
    print(f"Loaded files: {len(loaded_tables)}")

    for table in loaded_tables:
        print(f"\nFile: {table.path.name} ({table.extension})")
        df_pending = table.dataframe
        print(df_pending.head())

    if dates_range:
        print(f"Requested date range: {dates_range[0]} -> {dates_range[1]}")
    

    # Header row detection
    # Detect header row in Mizrachi export via NaN-first-row signature.
    header_row_idx = detect_header_row_mizrachi_case(df_pending)
    df_pending = apply_detected_header(df_pending, header_row_idx)

In [79]:
loaded_tables = load_mizrachi_tables(folder=path_to_folder, recursive=False)
print(f"Loaded files: {len(loaded_tables)}")

for table in loaded_tables:
    print(f"\nFile: {table.path.name} ({table.extension})")
    df_pending = table.dataframe
    print(df_pending.head())

if dates_range:
    print(f"Requested date range: {dates_range[0]} -> {dates_range[1]}")


# Header row detection
# Detect header row in Mizrachi export via NaN-first-row signature.
header_row_idx = detect_header_row_mizrachi_case(df_pending)
df_pending = apply_detected_header(df_pending, header_row_idx)

Loaded files: 1

File: AccountActivity (1).xls (.xls)
                0          1                    2               3       4  \
0    יתרה בחשבון:   29856.69             לתאריך -  05/03/26 23:15     NaN
1    מסגרת אשראי:   20000.00                  NaN             NaN     NaN
2  תנועות אחרונות        NaN                  NaN             NaN     NaN
3           תאריך  תאריך ערך            סוג תנועה            זכות    חובה
4        10/12/25        NaN  ביצוע הוראת קבע (י)             NaN  600.00

           5       6            __source_file  \
0        NaN     NaN  AccountActivity (1).xls
1        NaN     NaN  AccountActivity (1).xls
2        NaN     NaN  AccountActivity (1).xls
3  יתרה בש"ח  אסמכתא  AccountActivity (1).xls
4    9451.53      29  AccountActivity (1).xls

                                       __source_path __source_ext  \
0  C:\Users\shai\Documents\personal\personal_proj...         .xls
1  C:\Users\shai\Documents\personal\personal_proj...         .xls
2  C:\Users\shai\Documents\personal\personal_proj...         .xls
3  C:\Users\shai\Documents\personal\personal_proj...         .xls
4  C:\Users\shai\Documents\personal\personal_proj...         .xls

                __source_rule
0  mizrachi_read_html_table_1
1  mizrachi_read_html_table_1
2  mizrachi_read_html_table_1
3  mizrachi_read_html_table_1
4  mizrachi_read_html_table_1
Requested date range: 01/01/2026 -> 01/03/2026

In [80]:
df_pending

,תאריך,תאריך ערך,סוג תנועה,זכות,חובה,"יתרה בש""ח",אסמכתא,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_projects\ynab-israel-consolidator\private_data\incoming\bank_mizrachi\AccountActivity (1).xls,.xls,mizrachi_read_html_table_1
0,10/12/25,NaN,ביצוע הוראת קבע (י),NaN,600.00,9451.53,29,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
1,10/12/25,NaN,הרשאה ישראכרט (י),NaN,2874.04,NaN,20543,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
2,10/12/25,NaN,"מור גמל ופנסיה בע""מ(י)",NaN,1000.00,5577.49,57318,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
3,11/12/25,NaN,טן חברה לדלק (י),NaN,481.84,5095.65,27839,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
4,15/12/25,NaN,הרשאה מקס איט פיננס(י),NaN,7868.72,-2773.07,34685,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
5,16/12/25,NaN,זיכוי - בנק הפועלים(י),3000.00,NaN,226.93,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
6,21/12/25,NaN,ב. לאומי- קיצבת ילד(י),112.00,NaN,338.93,13104,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
7,01/01/26,NaN,"ריבית עו""ש",13.72,NaN,352.65,55555555,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
8,04/01/26,NaN,זיכוי - בנק הפועלים(י),3200.00,NaN,NaN,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
9,04/01/26,NaN,זיכוי - בנק הפועלים(י),5000.00,NaN,8552.65,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
10,11/01/26,NaN,ביצוע הוראת קבע (י),NaN,600.00,NaN,29,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
11,11/01/26,NaN,הרשאה ישראכרט (י),NaN,2504.63,NaN,20543,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
12,11/01/26,NaN,טן חברה לדלק (י),NaN,476.61,NaN,27839,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
13,11/01/26,NaN,"מור גמל ופנסיה בע""מ(י)",NaN,800.00,4171.41,57318,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
14,12/01/26,NaN,זיכוי - בנק הפועלים(י),4990.00,NaN,9161.41,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
15,15/01/26,NaN,הרשאה מקס איט פיננס(י),NaN,5875.55,3285.86,34685,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
16,20/01/26,NaN,ב. לאומי- קיצבת ילד(י),115.00,NaN,3400.86,13104,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
17,01/02/26,NaN,זיכוי - בנק הפועלים(י),5000.00,NaN,8400.86,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
18,04/02/26,NaN,זיכוי - בנק הפועלים(י),5000.00,NaN,13400.86,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
19,06/02/26,NaN,הרשאה מקס איט פיננס(י),NaN,62.78,13338.08,34685,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
20,08/02/26,NaN,זיכוי - בנק הפועלים(י),17000.00,NaN,30338.08,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
21,10/02/26,NaN,ביטוח לאומי חד פעמי(י),20315.00,NaN,NaN,63051,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
22,10/02/26,NaN,ביצוע הוראת קבע (י),NaN,600.00,NaN,29,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
23,10/02/26,NaN,הרשאה ישראכרט (י),NaN,3427.00,NaN,20543,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
24,10/02/26,NaN,הרשאה מקס איט פיננס(י),NaN,500.00,NaN,34685,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
25,10/02/26,NaN,"מור גמל ופנסיה בע""מ(י)",NaN,800.00,45326.08,57318,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
26,13/02/26,NaN,ביטוח לאומי חד פעמי(י),946.00,NaN,NaN,63051,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
27,13/02/26,NaN,העברה באינטרנט (י),NaN,2000.00,44272.08,6715,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
28,15/02/26,NaN,הרשאה מקס איט פיננס(י),NaN,12989.39,NaN,34685,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
29,15/02/26,NaN,העברה באינטרנט (י),NaN,1400.00,29882.69,25643,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
30,20/02/26,NaN,ב. לאומי- קיצבת ילד(י),115.00,NaN,29997.69,13104,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
31,25/02/26,NaN,ביטוח לאומי חד פעמי(י),219.00,NaN,30216.69,63051,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
32,תנועות היום,NaN,NaN,NaN,NaN,NaN,NaN,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
33,תנועות היום הן תנועות בחשבון שבוצעו ביום העסקי...,NaN,NaN,NaN,NaN,NaN,NaN,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1

In [81]:
GLOBAL_TRNASLATION_MAP = {
    'תאריך': 'Date',
    'סוג תנועה': 'Payee',
    'זכות': 'Inflow',
    'חובה': 'Outflow'
}

In [82]:
DATE_FORMAT = '%d/%m/%Y'

In [83]:
pd.to_datetime(df_pending['Date'], format=DATE_FORMAT).dt.strftime(DATE_FORMAT)

KeyError: 'Date'

In [84]:
df_pending.columns = df_pending.columns.map(GLOBAL_TRNASLATION_MAP)

In [85]:
pd.to_datetime(df_pending['Date'], format=DATE_FORMAT).dt.strftime(DATE_FORMAT)

ValueError: time data "10/12/25" doesn't match format "%d/%m/%Y", at position 0. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [86]:
1+1

2

In [87]:
pd

In [88]:
pd.to_datetime(
    df_pending["Date"].astype(str).str.strip(),
    format=DATE_FORMAT,
    errors="coerce",
)

0    NaT
1    NaT
2    NaT
3    NaT
4    NaT
5    NaT
6    NaT
7    NaT
8    NaT
9    NaT
10   NaT
11   NaT
12   NaT
13   NaT
14   NaT
15   NaT
16   NaT
17   NaT
18   NaT
19   NaT
20   NaT
21   NaT
22   NaT
23   NaT
24   NaT
25   NaT
26   NaT
27   NaT
28   NaT
29   NaT
30   NaT
31   NaT
32   NaT
33   NaT
Name: Date, dtype: datetime64[ns]

In [89]:
pd.to_datetime(df_pending["Date"].astype(str).str.strip(), format="%d/%m/%y", errors="coerce")

0    2025-12-10
1    2025-12-10
2    2025-12-10
3    2025-12-11
4    2025-12-15
5    2025-12-16
6    2025-12-21
7    2026-01-01
8    2026-01-04
9    2026-01-04
10   2026-01-11
11   2026-01-11
12   2026-01-11
13   2026-01-11
14   2026-01-12
15   2026-01-15
16   2026-01-20
17   2026-02-01
18   2026-02-04
19   2026-02-06
20   2026-02-08
21   2026-02-10
22   2026-02-10
23   2026-02-10
24   2026-02-10
25   2026-02-10
26   2026-02-13
27   2026-02-13
28   2026-02-15
29   2026-02-15
30   2026-02-20
31   2026-02-25
32          NaT
33          NaT
Name: Date, dtype: datetime64[ns]

In [90]:
from etl_sources.mizrachi_reader import load_mizrachi_tables
import pandas as pd

GLOBAL_TRNASLATION_MAP = {
    'תאריך': 'Date',
    'סוג תנועה': 'Payee',
    'זכות': 'Inflow',
    'חובה': 'Outflow'
}

DATE_FORMAT = '%d/%m/%Y'

def _dedupe_column_names(names: list[str]) -> list[str]:
    seen_counts: dict[str, int] = {}
    deduped: list[str] = []

    for name in names:
        count = seen_counts.get(name, 0) + 1
        seen_counts[name] = count
        deduped.append(name if count == 1 else f"{name}_{count}")

    return deduped


def parse_mizrachi_dates(raw_date_col: pd.Series, date_format: str = '%d/%m/%Y') -> pd.Series:
    # Clean raw values
    s = raw_date_col.astype(str).str.strip()
    s = s.replace({"": pd.NA, "nan": pd.NA, "None": pd.NA})
    # First pass: dd/mm/yy
    parsed = pd.to_datetime(s, format=date_format, errors="coerce")
    # Second pass (only failed rows): dd/mm/yyyy
    missing = parsed.isna()
    parsed.loc[missing] = pd.to_datetime(
        s.loc[missing],
        format=date_format,
        errors="coerce",
    )
    return parsed


def apply_detected_header(df: pd.DataFrame, header_row_idx: int) -> pd.DataFrame:
    if df.empty:
        return df.copy()

    if header_row_idx < 0 or header_row_idx >= len(df):
        raise ValueError(
            f"Detected header_row_idx {header_row_idx} is out of bounds for dataframe with {len(df)} rows."
        )

    raw_header = df.iloc[header_row_idx, :]
    cleaned_header = []
    for col_idx, value in enumerate(raw_header):
        if pd.isna(value):
            cleaned_header.append(f"unnamed_{col_idx}")
            continue

        header_name = str(value).strip()
        cleaned_header.append(header_name or f"unnamed_{col_idx}")

    normalized_columns = _dedupe_column_names(cleaned_header)
    normalized_df = df.iloc[header_row_idx + 1 :].copy().reset_index(drop=True)
    normalized_df.columns = normalized_columns
    return normalized_df


def detect_header_row_mizrachi_case(
    df: pd.DataFrame,
    default_row: int = 3,
    probe_rows: int = 1,
) -> int:
    """
    Heuristic:
    1) Find first column that has NaN in the first `probe_rows`.
    2) In that column, return first non-null row index.
    3) If no signal found, return default_row.
    """
    if df.empty:
        return default_row
    # Step 1: columns that look like your Mizrachi signature
    candidate_cols = [
        col for col in df.columns
        if df[col].iloc[:probe_rows].isna().any()
    ]
    # Step 2: find first non-null row in first matching column
    for col in candidate_cols:
        first_valid = df[col].first_valid_index()  # returns None if all null
        if first_valid is not None:
            return int(first_valid)
    return default_row

def main(path_to_folder: str, dates_range: tuple[str, str] | None = None) -> None:
    loaded_tables = load_mizrachi_tables(folder=path_to_folder, recursive=False)
    print(f"Loaded files: {len(loaded_tables)}")

    for table in loaded_tables:
        print(f"\nFile: {table.path.name} ({table.extension})")
        df_pending = table.dataframe
        print(df_pending.head())

    if dates_range:
        print(f"Requested date range: {dates_range[0]} -> {dates_range[1]}")
    

    # Detect header row in Mizrachi export via NaN-first-row signature.
    header_row_idx = detect_header_row_mizrachi_case(df_pending)

    df_pending = apply_detected_header(df_pending, header_row_idx)

    # find last footer of dataframe  using date column (non date values) or     
    # dataframe has been aligned to the header row

    # translating columns names using global mapping (for this project)
    df_pending.columns = df_pending.columns.map(GLOBAL_TRNASLATION_MAP)
    
    # Align dates to dd/mm/YYYY format + drop rows with invalid dates
    df_pending['Date'] = pd.to_datetime(df_pending['Date'], format=DATE_FORMAT).dt.strftime(DATE_FORMAT)
    parsed_dates = parse_mizrachi_dates(df_pending['Date'], DATE_FORMAT)



    #  
# STEP: parse date
# STEP: split inflow/outflow
# TODO: handle installment rows


if __name__ == "__main__":
    path_to_folder = r'C:\Users\shai\Documents\personal\personal_projects\ynab-israel-consolidator\private_data\incoming\bank_mizrachi'
    dates_range = ("01/01/2026", "01/03/2026")
    main(path_to_folder=path_to_folder, dates_range=dates_range)

Loaded files: 1

File: AccountActivity (1).xls (.xls)
                0          1                    2               3       4  \
0    יתרה בחשבון:   29856.69             לתאריך -  05/03/26 23:15     NaN
1    מסגרת אשראי:   20000.00                  NaN             NaN     NaN
2  תנועות אחרונות        NaN                  NaN             NaN     NaN
3           תאריך  תאריך ערך            סוג תנועה            זכות    חובה
4        10/12/25        NaN  ביצוע הוראת קבע (י)             NaN  600.00

           5       6            __source_file  \
0        NaN     NaN  AccountActivity (1).xls
1        NaN     NaN  AccountActivity (1).xls
2        NaN     NaN  AccountActivity (1).xls
3  יתרה בש"ח  אסמכתא  AccountActivity (1).xls
4    9451.53      29  AccountActivity (1).xls

                                       __source_path __source_ext  \
0  C:\Users\shai\Documents\personal\personal_proj...         .xls
1  C:\Users\shai\Documents\personal\personal_proj...         .xls
2  C:\Users\shai\Documents\personal\personal_proj...         .xls
3  C:\Users\shai\Documents\personal\personal_proj...         .xls
4  C:\Users\shai\Documents\personal\personal_proj...         .xls

                __source_rule
0  mizrachi_read_html_table_1
1  mizrachi_read_html_table_1
2  mizrachi_read_html_table_1
3  mizrachi_read_html_table_1
4  mizrachi_read_html_table_1
Requested date range: 01/01/2026 -> 01/03/2026

ValueError: time data "10/12/25" doesn't match format "%d/%m/%Y", at position 0. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [91]:
path_to_folder = r'C:\Users\shai\Documents\personal\personal_projects\ynab-israel-consolidator\private_data\incoming\bank_mizrachi'
dates_range = ("01/01/2026", "01/03/2026")

In [92]:
loaded_tables = load_mizrachi_tables(folder=path_to_folder, recursive=False)
print(f"Loaded files: {len(loaded_tables)}")

for table in loaded_tables:
    print(f"\nFile: {table.path.name} ({table.extension})")
    df_pending = table.dataframe
    print(df_pending.head())

if dates_range:
    print(f"Requested date range: {dates_range[0]} -> {dates_range[1]}")


# Detect header row in Mizrachi export via NaN-first-row signature.
header_row_idx = detect_header_row_mizrachi_case(df_pending)

df_pending = apply_detected_header(df_pending, header_row_idx)

# find last footer of dataframe  using date column (non date values) or     
# dataframe has been aligned to the header row

# translating columns names using global mapping (for this project)
df_pending.columns = df_pending.columns.map(GLOBAL_TRNASLATION_MAP)

# Align dates to dd/mm/YYYY format + drop rows with invalid dates
df_pending['Date'] = pd.to_datetime(df_pending['Date'], format=DATE_FORMAT).dt.strftime(DATE_FORMAT)
parsed_dates = parse_mizrachi_dates(df_pending['Date'], DATE_FORMAT)

Loaded files: 1

File: AccountActivity (1).xls (.xls)
                0          1                    2               3       4  \
0    יתרה בחשבון:   29856.69             לתאריך -  05/03/26 23:15     NaN
1    מסגרת אשראי:   20000.00                  NaN             NaN     NaN
2  תנועות אחרונות        NaN                  NaN             NaN     NaN
3           תאריך  תאריך ערך            סוג תנועה            זכות    חובה
4        10/12/25        NaN  ביצוע הוראת קבע (י)             NaN  600.00

           5       6            __source_file  \
0        NaN     NaN  AccountActivity (1).xls
1        NaN     NaN  AccountActivity (1).xls
2        NaN     NaN  AccountActivity (1).xls
3  יתרה בש"ח  אסמכתא  AccountActivity (1).xls
4    9451.53      29  AccountActivity (1).xls

                                       __source_path __source_ext  \
0  C:\Users\shai\Documents\personal\personal_proj...         .xls
1  C:\Users\shai\Documents\personal\personal_proj...         .xls
2  C:\Users\shai\Documents\personal\personal_proj...         .xls
3  C:\Users\shai\Documents\personal\personal_proj...         .xls
4  C:\Users\shai\Documents\personal\personal_proj...         .xls

                __source_rule
0  mizrachi_read_html_table_1
1  mizrachi_read_html_table_1
2  mizrachi_read_html_table_1
3  mizrachi_read_html_table_1
4  mizrachi_read_html_table_1
Requested date range: 01/01/2026 -> 01/03/2026

ValueError: time data "10/12/25" doesn't match format "%d/%m/%Y", at position 0. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [93]:
parsed_dates = parse_mizrachi_dates(df_pending['Date'], DATE_FORMAT)

In [94]:
parsed_dates

0    NaT
1    NaT
2    NaT
3    NaT
4    NaT
5    NaT
6    NaT
7    NaT
8    NaT
9    NaT
10   NaT
11   NaT
12   NaT
13   NaT
14   NaT
15   NaT
16   NaT
17   NaT
18   NaT
19   NaT
20   NaT
21   NaT
22   NaT
23   NaT
24   NaT
25   NaT
26   NaT
27   NaT
28   NaT
29   NaT
30   NaT
31   NaT
32   NaT
33   NaT
Name: Date, dtype: datetime64[ns]

In [95]:
|

SyntaxError: invalid syntax (2873296125.py, line 1)

In [96]:
from etl_sources.mizrachi_reader import load_mizrachi_tables
import pandas as pd

GLOBAL_TRNASLATION_MAP = {
    'תאריך': 'Date',
    'סוג תנועה': 'Payee',
    'זכות': 'Inflow',
    'חובה': 'Outflow'
}

DATE_FORMAT = '%d/%m/%Y'
MIZRACHI_DATE_FORMAT = '%d/%m/%y'

def _dedupe_column_names(names: list[str]) -> list[str]:
    seen_counts: dict[str, int] = {}
    deduped: list[str] = []

    for name in names:
        count = seen_counts.get(name, 0) + 1
        seen_counts[name] = count
        deduped.append(name if count == 1 else f"{name}_{count}")

    return deduped


def parse_mizrachi_dates(raw_date_col: pd.Series, date_format: str = '%d/%m/%Y') -> pd.Series:
    # Clean raw values
    s = raw_date_col.astype(str).str.strip()
    s = s.replace({"": pd.NA, "nan": pd.NA, "None": pd.NA})
    # First pass: dd/mm/yy
    parsed = pd.to_datetime(s, format=date_format, errors="coerce")
    # Second pass (only failed rows): dd/mm/yyyy
    missing = parsed.isna()
    parsed.loc[missing] = pd.to_datetime(
        s.loc[missing],
        format=date_format,
        errors="coerce",
    )
    return parsed


def apply_detected_header(df: pd.DataFrame, header_row_idx: int) -> pd.DataFrame:
    if df.empty:
        return df.copy()

    if header_row_idx < 0 or header_row_idx >= len(df):
        raise ValueError(
            f"Detected header_row_idx {header_row_idx} is out of bounds for dataframe with {len(df)} rows."
        )

    raw_header = df.iloc[header_row_idx, :]
    cleaned_header = []
    for col_idx, value in enumerate(raw_header):
        if pd.isna(value):
            cleaned_header.append(f"unnamed_{col_idx}")
            continue

        header_name = str(value).strip()
        cleaned_header.append(header_name or f"unnamed_{col_idx}")

    normalized_columns = _dedupe_column_names(cleaned_header)
    normalized_df = df.iloc[header_row_idx + 1 :].copy().reset_index(drop=True)
    normalized_df.columns = normalized_columns
    return normalized_df


def detect_header_row_mizrachi_case(
    df: pd.DataFrame,
    default_row: int = 3,
    probe_rows: int = 1,
) -> int:
    """
    Heuristic:
    1) Find first column that has NaN in the first `probe_rows`.
    2) In that column, return first non-null row index.
    3) If no signal found, return default_row.
    """
    if df.empty:
        return default_row
    # Step 1: columns that look like your Mizrachi signature
    candidate_cols = [
        col for col in df.columns
        if df[col].iloc[:probe_rows].isna().any()
    ]
    # Step 2: find first non-null row in first matching column
    for col in candidate_cols:
        first_valid = df[col].first_valid_index()  # returns None if all null
        if first_valid is not None:
            return int(first_valid)
    return default_row

def main(path_to_folder: str, dates_range: tuple[str, str] | None = None) -> None:
    loaded_tables = load_mizrachi_tables(folder=path_to_folder, recursive=False)
    print(f"Loaded files: {len(loaded_tables)}")

    for table in loaded_tables:
        print(f"\nFile: {table.path.name} ({table.extension})")
        df_pending = table.dataframe
        print(df_pending.head())

    if dates_range:
        print(f"Requested date range: {dates_range[0]} -> {dates_range[1]}")
    

    # Detect header row in Mizrachi export via NaN-first-row signature.
    header_row_idx = detect_header_row_mizrachi_case(df_pending)

    df_pending = apply_detected_header(df_pending, header_row_idx)

    # find last footer of dataframe  using date column (non date values) or     
    # dataframe has been aligned to the header row

    # translating columns names using global mapping (for this project)
    df_pending.columns = df_pending.columns.map(GLOBAL_TRNASLATION_MAP)
    
    # Align dates to dd/mm/YYYY format + drop rows with invalid dates
    parsed_dates = parse_mizrachi_dates(df_pending['Date'], MIZRACHI_DATE_FORMAT)



    #  
# STEP: parse date
# STEP: split inflow/outflow
# TODO: handle installment rows


if __name__ == "__main__":
    path_to_folder = r'C:\Users\shai\Documents\personal\personal_projects\ynab-israel-consolidator\private_data\incoming\bank_mizrachi'
    dates_range = ("01/01/2026", "01/03/2026")
    main(path_to_folder=path_to_folder, dates_range=dates_range)

Loaded files: 1

File: AccountActivity (1).xls (.xls)
                0          1                    2               3       4  \
0    יתרה בחשבון:   29856.69             לתאריך -  05/03/26 23:15     NaN
1    מסגרת אשראי:   20000.00                  NaN             NaN     NaN
2  תנועות אחרונות        NaN                  NaN             NaN     NaN
3           תאריך  תאריך ערך            סוג תנועה            זכות    חובה
4        10/12/25        NaN  ביצוע הוראת קבע (י)             NaN  600.00

           5       6            __source_file  \
0        NaN     NaN  AccountActivity (1).xls
1        NaN     NaN  AccountActivity (1).xls
2        NaN     NaN  AccountActivity (1).xls
3  יתרה בש"ח  אסמכתא  AccountActivity (1).xls
4    9451.53      29  AccountActivity (1).xls

                                       __source_path __source_ext  \
0  C:\Users\shai\Documents\personal\personal_proj...         .xls
1  C:\Users\shai\Documents\personal\personal_proj...         .xls
2  C:\Users\shai\Documents\personal\personal_proj...         .xls
3  C:\Users\shai\Documents\personal\personal_proj...         .xls
4  C:\Users\shai\Documents\personal\personal_proj...         .xls

                __source_rule
0  mizrachi_read_html_table_1
1  mizrachi_read_html_table_1
2  mizrachi_read_html_table_1
3  mizrachi_read_html_table_1
4  mizrachi_read_html_table_1
Requested date range: 01/01/2026 -> 01/03/2026

In [97]:
parsed_dates

0    NaT
1    NaT
2    NaT
3    NaT
4    NaT
5    NaT
6    NaT
7    NaT
8    NaT
9    NaT
10   NaT
11   NaT
12   NaT
13   NaT
14   NaT
15   NaT
16   NaT
17   NaT
18   NaT
19   NaT
20   NaT
21   NaT
22   NaT
23   NaT
24   NaT
25   NaT
26   NaT
27   NaT
28   NaT
29   NaT
30   NaT
31   NaT
32   NaT
33   NaT
Name: Date, dtype: datetime64[ns]

In [98]:
s =df_pending["Date"].astype(str).str.strip()

In [99]:
s

0                                              10/12/25
1                                              10/12/25
2                                              10/12/25
3                                              11/12/25
4                                              15/12/25
5                                              16/12/25
6                                              21/12/25
7                                              01/01/26
8                                              04/01/26
9                                              04/01/26
10                                             11/01/26
11                                             11/01/26
12                                             11/01/26
13                                             11/01/26
14                                             12/01/26
15                                             15/01/26
16                                             20/01/26
17                                             01/02/26
18                                             04/02/26
19                                             06/02/26
20                                             08/02/26
21                                             10/02/26
22                                             10/02/26
23                                             10/02/26
24                                             10/02/26
25                                             10/02/26
26                                             13/02/26
27                                             13/02/26
28                                             15/02/26
29                                             15/02/26
30                                             20/02/26
31                                             25/02/26
32                                          תנועות היום
33    תנועות היום הן תנועות בחשבון שבוצעו ביום העסקי...
Name: Date, dtype: object

In [100]:
s = s.replace({"": pd.NA, "nan": pd.NA, "None": pd.NA})

In [101]:
s

0                                              10/12/25
1                                              10/12/25
2                                              10/12/25
3                                              11/12/25
4                                              15/12/25
5                                              16/12/25
6                                              21/12/25
7                                              01/01/26
8                                              04/01/26
9                                              04/01/26
10                                             11/01/26
11                                             11/01/26
12                                             11/01/26
13                                             11/01/26
14                                             12/01/26
15                                             15/01/26
16                                             20/01/26
17                                             01/02/26
18                                             04/02/26
19                                             06/02/26
20                                             08/02/26
21                                             10/02/26
22                                             10/02/26
23                                             10/02/26
24                                             10/02/26
25                                             10/02/26
26                                             13/02/26
27                                             13/02/26
28                                             15/02/26
29                                             15/02/26
30                                             20/02/26
31                                             25/02/26
32                                          תנועות היום
33    תנועות היום הן תנועות בחשבון שבוצעו ביום העסקי...
Name: Date, dtype: object

In [102]:
pd.to_datetime(s, format=date_format, errors="coerce")

NameError: name 'date_format' is not defined

In [103]:
MIZRACHI_DATE_FORMAT = '%d/%m/%y'

In [104]:
pd.to_datetime(s, format=MIZRACHI_DATE_FORMAT, errors="coerce")

0    2025-12-10
1    2025-12-10
2    2025-12-10
3    2025-12-11
4    2025-12-15
5    2025-12-16
6    2025-12-21
7    2026-01-01
8    2026-01-04
9    2026-01-04
10   2026-01-11
11   2026-01-11
12   2026-01-11
13   2026-01-11
14   2026-01-12
15   2026-01-15
16   2026-01-20
17   2026-02-01
18   2026-02-04
19   2026-02-06
20   2026-02-08
21   2026-02-10
22   2026-02-10
23   2026-02-10
24   2026-02-10
25   2026-02-10
26   2026-02-13
27   2026-02-13
28   2026-02-15
29   2026-02-15
30   2026-02-20
31   2026-02-25
32          NaT
33          NaT
Name: Date, dtype: datetime64[ns]

In [105]:
parsed = pd.to_datetime(s, format=MIZRACHI_DATE_FORMAT, errors="coerce")

In [106]:
parsed

0    2025-12-10
1    2025-12-10
2    2025-12-10
3    2025-12-11
4    2025-12-15
5    2025-12-16
6    2025-12-21
7    2026-01-01
8    2026-01-04
9    2026-01-04
10   2026-01-11
11   2026-01-11
12   2026-01-11
13   2026-01-11
14   2026-01-12
15   2026-01-15
16   2026-01-20
17   2026-02-01
18   2026-02-04
19   2026-02-06
20   2026-02-08
21   2026-02-10
22   2026-02-10
23   2026-02-10
24   2026-02-10
25   2026-02-10
26   2026-02-13
27   2026-02-13
28   2026-02-15
29   2026-02-15
30   2026-02-20
31   2026-02-25
32          NaT
33          NaT
Name: Date, dtype: datetime64[ns]

In [107]:
    missing = parsed.isna()
    parsed.loc[missing] = pd.to_datetime(
        s.loc[missing],
        format=date_format,
        errors="coerce",
    )

NameError: name 'date_format' is not defined

In [108]:
    missing = parsed.isna()
    parsed.loc[missing] = pd.to_datetime(
        s.loc[missing],
        format=MIZRACHI_DATE_FORMAT,
        errors="coerce",
    )

In [109]:
parsed

0    2025-12-10
1    2025-12-10
2    2025-12-10
3    2025-12-11
4    2025-12-15
5    2025-12-16
6    2025-12-21
7    2026-01-01
8    2026-01-04
9    2026-01-04
10   2026-01-11
11   2026-01-11
12   2026-01-11
13   2026-01-11
14   2026-01-12
15   2026-01-15
16   2026-01-20
17   2026-02-01
18   2026-02-04
19   2026-02-06
20   2026-02-08
21   2026-02-10
22   2026-02-10
23   2026-02-10
24   2026-02-10
25   2026-02-10
26   2026-02-13
27   2026-02-13
28   2026-02-15
29   2026-02-15
30   2026-02-20
31   2026-02-25
32          NaT
33          NaT
Name: Date, dtype: datetime64[ns]

In [110]:
s.loc[missing]

32                                          תנועות היום
33    תנועות היום הן תנועות בחשבון שבוצעו ביום העסקי...
Name: Date, dtype: object

Restarted venv_nadlan_311 (Python 3.11.13)

In [1]:
from etl_sources.mizrachi_reader import load_mizrachi_tables
import pandas as pd

GLOBAL_TRNASLATION_MAP = {
    'תאריך': 'Date',
    'סוג תנועה': 'Payee',
    'זכות': 'Inflow',
    'חובה': 'Outflow'
}

DATE_FORMAT = '%d/%m/%Y'
MIZRACHI_DATE_FORMAT = '%d/%m/%y'

def _dedupe_column_names(names: list[str]) -> list[str]:
    seen_counts: dict[str, int] = {}
    deduped: list[str] = []

    for name in names:
        count = seen_counts.get(name, 0) + 1
        seen_counts[name] = count
        deduped.append(name if count == 1 else f"{name}_{count}")

    return deduped


def parse_mizrachi_dates(raw_date_col: pd.Series, date_format: str = '%d/%m/%Y') -> pd.Series:
    # Clean raw values
    s = raw_date_col.astype(str).str.strip()
    s = s.replace({"": pd.NA, "nan": pd.NA, "None": pd.NA})
    # First pass: dd/mm/yy
    parsed = pd.to_datetime(s, format=date_format, errors="coerce")
    # Second pass (only failed rows): dd/mm/yyyy
    missing = parsed.isna()
    parsed.loc[missing] = pd.to_datetime(
        s.loc[missing],
        format=date_format,
        errors="coerce",
    )
    return parsed


def apply_detected_header(df: pd.DataFrame, header_row_idx: int) -> pd.DataFrame:
    if df.empty:
        return df.copy()

    if header_row_idx < 0 or header_row_idx >= len(df):
        raise ValueError(
            f"Detected header_row_idx {header_row_idx} is out of bounds for dataframe with {len(df)} rows."
        )

    raw_header = df.iloc[header_row_idx, :]
    cleaned_header = []
    for col_idx, value in enumerate(raw_header):
        if pd.isna(value):
            cleaned_header.append(f"unnamed_{col_idx}")
            continue

        header_name = str(value).strip()
        cleaned_header.append(header_name or f"unnamed_{col_idx}")

    normalized_columns = _dedupe_column_names(cleaned_header)
    normalized_df = df.iloc[header_row_idx + 1 :].copy().reset_index(drop=True)
    normalized_df.columns = normalized_columns
    return normalized_df


def detect_header_row_mizrachi_case(
    df: pd.DataFrame,
    default_row: int = 3,
    probe_rows: int = 1,
) -> int:
    """
    Heuristic:
    1) Find first column that has NaN in the first `probe_rows`.
    2) In that column, return first non-null row index.
    3) If no signal found, return default_row.
    """
    if df.empty:
        return default_row
    # Step 1: columns that look like your Mizrachi signature
    candidate_cols = [
        col for col in df.columns
        if df[col].iloc[:probe_rows].isna().any()
    ]
    # Step 2: find first non-null row in first matching column
    for col in candidate_cols:
        first_valid = df[col].first_valid_index()  # returns None if all null
        if first_valid is not None:
            return int(first_valid)
    return default_row

def main(path_to_folder: str, dates_range: tuple[str, str] | None = None) -> None:
    loaded_tables = load_mizrachi_tables(folder=path_to_folder, recursive=False)
    print(f"Loaded files: {len(loaded_tables)}")

    for table in loaded_tables:
        print(f"\nFile: {table.path.name} ({table.extension})")
        df_pending = table.dataframe
        print(df_pending.head())

    if dates_range:
        print(f"Requested date range: {dates_range[0]} -> {dates_range[1]}")
    

    # Detect header row in Mizrachi export via NaN-first-row signature.
    header_row_idx = detect_header_row_mizrachi_case(df_pending)

    df_pending = apply_detected_header(df_pending, header_row_idx)

    # find last footer of dataframe  using date column (non date values) or     
    # dataframe has been aligned to the header row

    # translating columns names using global mapping (for this project)
    df_pending.columns = df_pending.columns.map(GLOBAL_TRNASLATION_MAP)
    
    # Align dates to dd/mm/YYYY format + drop rows with invalid dates
    parsed_dates = parse_mizrachi_dates(df_pending['Date'], date_format=MIZRACHI_DATE_FORMAT)



    #  
# STEP: parse date
# STEP: split inflow/outflow
# TODO: handle installment rows


if __name__ == "__main__":
    path_to_folder = r'C:\Users\shai\Documents\personal\personal_projects\ynab-israel-consolidator\private_data\incoming\bank_mizrachi'
    dates_range = ("01/01/2026", "01/03/2026")
    main(path_to_folder=path_to_folder, dates_range=dates_range)

Loaded files: 1

File: AccountActivity (1).xls (.xls)
                0          1                    2               3       4  \
0    יתרה בחשבון:   29856.69             לתאריך -  05/03/26 23:15     NaN
1    מסגרת אשראי:   20000.00                  NaN             NaN     NaN
2  תנועות אחרונות        NaN                  NaN             NaN     NaN
3           תאריך  תאריך ערך            סוג תנועה            זכות    חובה
4        10/12/25        NaN  ביצוע הוראת קבע (י)             NaN  600.00

           5       6            __source_file  \
0        NaN     NaN  AccountActivity (1).xls
1        NaN     NaN  AccountActivity (1).xls
2        NaN     NaN  AccountActivity (1).xls
3  יתרה בש"ח  אסמכתא  AccountActivity (1).xls
4    9451.53      29  AccountActivity (1).xls

                                       __source_path __source_ext  \
0  C:\Users\shai\Documents\personal\personal_proj...         .xls
1  C:\Users\shai\Documents\personal\personal_proj...         .xls
2  C:\Users\shai\Documents\personal\personal_proj...         .xls
3  C:\Users\shai\Documents\personal\personal_proj...         .xls
4  C:\Users\shai\Documents\personal\personal_proj...         .xls

                __source_rule
0  mizrachi_read_html_table_1
1  mizrachi_read_html_table_1
2  mizrachi_read_html_table_1
3  mizrachi_read_html_table_1
4  mizrachi_read_html_table_1
Requested date range: 01/01/2026 -> 01/03/2026

In [2]:
loaded_tables = load_mizrachi_tables(folder=path_to_folder, recursive=False)
print(f"Loaded files: {len(loaded_tables)}")

for table in loaded_tables:
    print(f"\nFile: {table.path.name} ({table.extension})")
    df_pending = table.dataframe
    print(df_pending.head())

if dates_range:
    print(f"Requested date range: {dates_range[0]} -> {dates_range[1]}")


# Detect header row in Mizrachi export via NaN-first-row signature.
header_row_idx = detect_header_row_mizrachi_case(df_pending)

df_pending = apply_detected_header(df_pending, header_row_idx)

# find last footer of dataframe  using date column (non date values) or     
# dataframe has been aligned to the header row

# translating columns names using global mapping (for this project)
df_pending.columns = df_pending.columns.map(GLOBAL_TRNASLATION_MAP)

# Align dates to dd/mm/YYYY format + drop rows with invalid dates
parsed_dates = parse_mizrachi_dates(df_pending['Date'], date_format=MIZRACHI_DATE_FORMAT)

Loaded files: 1

File: AccountActivity (1).xls (.xls)
                0          1                    2               3       4  \
0    יתרה בחשבון:   29856.69             לתאריך -  05/03/26 23:15     NaN
1    מסגרת אשראי:   20000.00                  NaN             NaN     NaN
2  תנועות אחרונות        NaN                  NaN             NaN     NaN
3           תאריך  תאריך ערך            סוג תנועה            זכות    חובה
4        10/12/25        NaN  ביצוע הוראת קבע (י)             NaN  600.00

           5       6            __source_file  \
0        NaN     NaN  AccountActivity (1).xls
1        NaN     NaN  AccountActivity (1).xls
2        NaN     NaN  AccountActivity (1).xls
3  יתרה בש"ח  אסמכתא  AccountActivity (1).xls
4    9451.53      29  AccountActivity (1).xls

                                       __source_path __source_ext  \
0  C:\Users\shai\Documents\personal\personal_proj...         .xls
1  C:\Users\shai\Documents\personal\personal_proj...         .xls
2  C:\Users\shai\Documents\personal\personal_proj...         .xls
3  C:\Users\shai\Documents\personal\personal_proj...         .xls
4  C:\Users\shai\Documents\personal\personal_proj...         .xls

                __source_rule
0  mizrachi_read_html_table_1
1  mizrachi_read_html_table_1
2  mizrachi_read_html_table_1
3  mizrachi_read_html_table_1
4  mizrachi_read_html_table_1
Requested date range: 01/01/2026 -> 01/03/2026

In [3]:
parsed_dates

0    2025-12-10
1    2025-12-10
2    2025-12-10
3    2025-12-11
4    2025-12-15
5    2025-12-16
6    2025-12-21
7    2026-01-01
8    2026-01-04
9    2026-01-04
10   2026-01-11
11   2026-01-11
12   2026-01-11
13   2026-01-11
14   2026-01-12
15   2026-01-15
16   2026-01-20
17   2026-02-01
18   2026-02-04
19   2026-02-06
20   2026-02-08
21   2026-02-10
22   2026-02-10
23   2026-02-10
24   2026-02-10
25   2026-02-10
26   2026-02-13
27   2026-02-13
28   2026-02-15
29   2026-02-15
30   2026-02-20
31   2026-02-25
32          NaT
33          NaT
Name: Date, dtype: datetime64[ns]

In [4]:
valid_mask = parsed_dates.notna()
df_pending = df_pending.loc[valid_mask].copy()

In [5]:
valid_mask

0      True
1      True
2      True
3      True
4      True
5      True
6      True
7      True
8      True
9      True
10     True
11     True
12     True
13     True
14     True
15     True
16     True
17     True
18     True
19     True
20     True
21     True
22     True
23     True
24     True
25     True
26     True
27     True
28     True
29     True
30     True
31     True
32    False
33    False
Name: Date, dtype: bool

In [6]:
df_pending

,Date,NaN,Payee,Inflow,Outflow,NaN,NaN,NaN,NaN,NaN,NaN
0,10/12/25,NaN,ביצוע הוראת קבע (י),NaN,600.00,9451.53,29,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
1,10/12/25,NaN,הרשאה ישראכרט (י),NaN,2874.04,NaN,20543,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
2,10/12/25,NaN,"מור גמל ופנסיה בע""מ(י)",NaN,1000.00,5577.49,57318,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
3,11/12/25,NaN,טן חברה לדלק (י),NaN,481.84,5095.65,27839,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
4,15/12/25,NaN,הרשאה מקס איט פיננס(י),NaN,7868.72,-2773.07,34685,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
5,16/12/25,NaN,זיכוי - בנק הפועלים(י),3000.00,NaN,226.93,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
6,21/12/25,NaN,ב. לאומי- קיצבת ילד(י),112.00,NaN,338.93,13104,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
7,01/01/26,NaN,"ריבית עו""ש",13.72,NaN,352.65,55555555,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
8,04/01/26,NaN,זיכוי - בנק הפועלים(י),3200.00,NaN,NaN,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
9,04/01/26,NaN,זיכוי - בנק הפועלים(י),5000.00,NaN,8552.65,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
10,11/01/26,NaN,ביצוע הוראת קבע (י),NaN,600.00,NaN,29,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
11,11/01/26,NaN,הרשאה ישראכרט (י),NaN,2504.63,NaN,20543,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
12,11/01/26,NaN,טן חברה לדלק (י),NaN,476.61,NaN,27839,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
13,11/01/26,NaN,"מור גמל ופנסיה בע""מ(י)",NaN,800.00,4171.41,57318,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
14,12/01/26,NaN,זיכוי - בנק הפועלים(י),4990.00,NaN,9161.41,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
15,15/01/26,NaN,הרשאה מקס איט פיננס(י),NaN,5875.55,3285.86,34685,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
16,20/01/26,NaN,ב. לאומי- קיצבת ילד(י),115.00,NaN,3400.86,13104,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
17,01/02/26,NaN,זיכוי - בנק הפועלים(י),5000.00,NaN,8400.86,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
18,04/02/26,NaN,זיכוי - בנק הפועלים(י),5000.00,NaN,13400.86,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
19,06/02/26,NaN,הרשאה מקס איט פיננס(י),NaN,62.78,13338.08,34685,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
20,08/02/26,NaN,זיכוי - בנק הפועלים(י),17000.00,NaN,30338.08,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
21,10/02/26,NaN,ביטוח לאומי חד פעמי(י),20315.00,NaN,NaN,63051,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
22,10/02/26,NaN,ביצוע הוראת קבע (י),NaN,600.00,NaN,29,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
23,10/02/26,NaN,הרשאה ישראכרט (י),NaN,3427.00,NaN,20543,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
24,10/02/26,NaN,הרשאה מקס איט פיננס(י),NaN,500.00,NaN,34685,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
25,10/02/26,NaN,"מור גמל ופנסיה בע""מ(י)",NaN,800.00,45326.08,57318,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
26,13/02/26,NaN,ביטוח לאומי חד פעמי(י),946.00,NaN,NaN,63051,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
27,13/02/26,NaN,העברה באינטרנט (י),NaN,2000.00,44272.08,6715,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
28,15/02/26,NaN,הרשאה מקס איט פיננס(י),NaN,12989.39,NaN,34685,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
29,15/02/26,NaN,העברה באינטרנט (י),NaN,1400.00,29882.69,25643,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
30,20/02/26,NaN,ב. לאומי- קיצבת ילד(י),115.00,NaN,29997.69,13104,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
31,25/02/26,NaN,ביטוח לאומי חד פעמי(י),219.00,NaN,30216.69,63051,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1

In [7]:
parsed_dates.loc[valid_mask].dt.strftime(DATE_FORMAT)

0     10/12/2025
1     10/12/2025
2     10/12/2025
3     11/12/2025
4     15/12/2025
5     16/12/2025
6     21/12/2025
7     01/01/2026
8     04/01/2026
9     04/01/2026
10    11/01/2026
11    11/01/2026
12    11/01/2026
13    11/01/2026
14    12/01/2026
15    15/01/2026
16    20/01/2026
17    01/02/2026
18    04/02/2026
19    06/02/2026
20    08/02/2026
21    10/02/2026
22    10/02/2026
23    10/02/2026
24    10/02/2026
25    10/02/2026
26    13/02/2026
27    13/02/2026
28    15/02/2026
29    15/02/2026
30    20/02/2026
31    25/02/2026
Name: Date, dtype: object

In [8]:
df_pending["Date"] = parsed_dates.loc[valid_mask].dt.strftime(DATE_FORMAT)

In [9]:
df_pending

,Date,NaN,Payee,Inflow,Outflow,NaN,NaN,NaN,NaN,NaN,NaN
0,10/12/2025,NaN,ביצוע הוראת קבע (י),NaN,600.00,9451.53,29,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
1,10/12/2025,NaN,הרשאה ישראכרט (י),NaN,2874.04,NaN,20543,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
2,10/12/2025,NaN,"מור גמל ופנסיה בע""מ(י)",NaN,1000.00,5577.49,57318,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
3,11/12/2025,NaN,טן חברה לדלק (י),NaN,481.84,5095.65,27839,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
4,15/12/2025,NaN,הרשאה מקס איט פיננס(י),NaN,7868.72,-2773.07,34685,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
5,16/12/2025,NaN,זיכוי - בנק הפועלים(י),3000.00,NaN,226.93,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
6,21/12/2025,NaN,ב. לאומי- קיצבת ילד(י),112.00,NaN,338.93,13104,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
7,01/01/2026,NaN,"ריבית עו""ש",13.72,NaN,352.65,55555555,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
8,04/01/2026,NaN,זיכוי - בנק הפועלים(י),3200.00,NaN,NaN,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
9,04/01/2026,NaN,זיכוי - בנק הפועלים(י),5000.00,NaN,8552.65,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
10,11/01/2026,NaN,ביצוע הוראת קבע (י),NaN,600.00,NaN,29,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
11,11/01/2026,NaN,הרשאה ישראכרט (י),NaN,2504.63,NaN,20543,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
12,11/01/2026,NaN,טן חברה לדלק (י),NaN,476.61,NaN,27839,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
13,11/01/2026,NaN,"מור גמל ופנסיה בע""מ(י)",NaN,800.00,4171.41,57318,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
14,12/01/2026,NaN,זיכוי - בנק הפועלים(י),4990.00,NaN,9161.41,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
15,15/01/2026,NaN,הרשאה מקס איט פיננס(י),NaN,5875.55,3285.86,34685,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
16,20/01/2026,NaN,ב. לאומי- קיצבת ילד(י),115.00,NaN,3400.86,13104,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
17,01/02/2026,NaN,זיכוי - בנק הפועלים(י),5000.00,NaN,8400.86,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
18,04/02/2026,NaN,זיכוי - בנק הפועלים(י),5000.00,NaN,13400.86,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
19,06/02/2026,NaN,הרשאה מקס איט פיננס(י),NaN,62.78,13338.08,34685,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
20,08/02/2026,NaN,זיכוי - בנק הפועלים(י),17000.00,NaN,30338.08,99012,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
21,10/02/2026,NaN,ביטוח לאומי חד פעמי(י),20315.00,NaN,NaN,63051,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
22,10/02/2026,NaN,ביצוע הוראת קבע (י),NaN,600.00,NaN,29,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
23,10/02/2026,NaN,הרשאה ישראכרט (י),NaN,3427.00,NaN,20543,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
24,10/02/2026,NaN,הרשאה מקס איט פיננס(י),NaN,500.00,NaN,34685,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
25,10/02/2026,NaN,"מור גמל ופנסיה בע""מ(י)",NaN,800.00,45326.08,57318,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
26,13/02/2026,NaN,ביטוח לאומי חד פעמי(י),946.00,NaN,NaN,63051,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
27,13/02/2026,NaN,העברה באינטרנט (י),NaN,2000.00,44272.08,6715,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
28,15/02/2026,NaN,הרשאה מקס איט פיננס(י),NaN,12989.39,NaN,34685,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
29,15/02/2026,NaN,העברה באינטרנט (י),NaN,1400.00,29882.69,25643,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
30,20/02/2026,NaN,ב. לאומי- קיצבת ילד(י),115.00,NaN,29997.69,13104,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1
31,25/02/2026,NaN,ביטוח לאומי חד פעמי(י),219.00,NaN,30216.69,63051,AccountActivity (1).xls,C:\Users\shai\Documents\personal\personal_proj...,.xls,mizrachi_read_html_table_1

In [10]:
df_pending = df_pending[GLOBAL_TRNASLATION_MAP.values()]

In [11]:
df_pending

          Date                   Payee    Inflow   Outflow
0   10/12/2025     ביצוע הוראת קבע (י)       NaN    600.00
1   10/12/2025       הרשאה ישראכרט (י)       NaN   2874.04
2   10/12/2025  מור גמל ופנסיה בע"מ(י)       NaN   1000.00
3   11/12/2025        טן חברה לדלק (י)       NaN    481.84
4   15/12/2025  הרשאה מקס איט פיננס(י)       NaN   7868.72
5   16/12/2025  זיכוי - בנק הפועלים(י)   3000.00       NaN
6   21/12/2025  ב. לאומי- קיצבת ילד(י)    112.00       NaN
7   01/01/2026              ריבית עו"ש     13.72       NaN
8   04/01/2026  זיכוי - בנק הפועלים(י)   3200.00       NaN
9   04/01/2026  זיכוי - בנק הפועלים(י)   5000.00       NaN
10  11/01/2026     ביצוע הוראת קבע (י)       NaN    600.00
11  11/01/2026       הרשאה ישראכרט (י)       NaN   2504.63
12  11/01/2026        טן חברה לדלק (י)       NaN    476.61
13  11/01/2026  מור גמל ופנסיה בע"מ(י)       NaN    800.00
14  12/01/2026  זיכוי - בנק הפועלים(י)   4990.00       NaN
15  15/01/2026  הרשאה מקס איט פיננס(י)       NaN   5875.55
16  20/01/2026  ב. לאומי- קיצבת ילד(י)    115.00       NaN
17  01/02/2026  זיכוי - בנק הפועלים(י)   5000.00       NaN
18  04/02/2026  זיכוי - בנק הפועלים(י)   5000.00       NaN
19  06/02/2026  הרשאה מקס איט פיננס(י)       NaN     62.78
20  08/02/2026  זיכוי - בנק הפועלים(י)  17000.00       NaN
21  10/02/2026  ביטוח לאומי חד פעמי(י)  20315.00       NaN
22  10/02/2026     ביצוע הוראת קבע (י)       NaN    600.00
23  10/02/2026       הרשאה ישראכרט (י)       NaN   3427.00
24  10/02/2026  הרשאה מקס איט פיננס(י)       NaN    500.00
25  10/02/2026  מור גמל ופנסיה בע"מ(י)       NaN    800.00
26  13/02/2026  ביטוח לאומי חד פעמי(י)    946.00       NaN
27  13/02/2026      העברה באינטרנט (י)       NaN   2000.00
28  15/02/2026  הרשאה מקס איט פיננס(י)       NaN  12989.39
29  15/02/2026      העברה באינטרנט (י)       NaN   1400.00
30  20/02/2026  ב. לאומי- קיצבת ילד(י)    115.00       NaN
31  25/02/2026  ביטוח לאומי חד פעמי(י)    219.00       NaN

In [12]:
df_pending = df_pending[[column for column in GLOBAL_TRNASLATION_MAP.values() if column in df_pending.columns]]

In [13]:
df_pending

          Date                   Payee    Inflow   Outflow
0   10/12/2025     ביצוע הוראת קבע (י)       NaN    600.00
1   10/12/2025       הרשאה ישראכרט (י)       NaN   2874.04
2   10/12/2025  מור גמל ופנסיה בע"מ(י)       NaN   1000.00
3   11/12/2025        טן חברה לדלק (י)       NaN    481.84
4   15/12/2025  הרשאה מקס איט פיננס(י)       NaN   7868.72
5   16/12/2025  זיכוי - בנק הפועלים(י)   3000.00       NaN
6   21/12/2025  ב. לאומי- קיצבת ילד(י)    112.00       NaN
7   01/01/2026              ריבית עו"ש     13.72       NaN
8   04/01/2026  זיכוי - בנק הפועלים(י)   3200.00       NaN
9   04/01/2026  זיכוי - בנק הפועלים(י)   5000.00       NaN
10  11/01/2026     ביצוע הוראת קבע (י)       NaN    600.00
11  11/01/2026       הרשאה ישראכרט (י)       NaN   2504.63
12  11/01/2026        טן חברה לדלק (י)       NaN    476.61
13  11/01/2026  מור גמל ופנסיה בע"מ(י)       NaN    800.00
14  12/01/2026  זיכוי - בנק הפועלים(י)   4990.00       NaN
15  15/01/2026  הרשאה מקס איט פיננס(י)       NaN   5875.55
16  20/01/2026  ב. לאומי- קיצבת ילד(י)    115.00       NaN
17  01/02/2026  זיכוי - בנק הפועלים(י)   5000.00       NaN
18  04/02/2026  זיכוי - בנק הפועלים(י)   5000.00       NaN
19  06/02/2026  הרשאה מקס איט פיננס(י)       NaN     62.78
20  08/02/2026  זיכוי - בנק הפועלים(י)  17000.00       NaN
21  10/02/2026  ביטוח לאומי חד פעמי(י)  20315.00       NaN
22  10/02/2026     ביצוע הוראת קבע (י)       NaN    600.00
23  10/02/2026       הרשאה ישראכרט (י)       NaN   3427.00
24  10/02/2026  הרשאה מקס איט פיננס(י)       NaN    500.00
25  10/02/2026  מור גמל ופנסיה בע"מ(י)       NaN    800.00
26  13/02/2026  ביטוח לאומי חד פעמי(י)    946.00       NaN
27  13/02/2026      העברה באינטרנט (י)       NaN   2000.00
28  15/02/2026  הרשאה מקס איט פיננס(י)       NaN  12989.39
29  15/02/2026      העברה באינטרנט (י)       NaN   1400.00
30  20/02/2026  ב. לאומי- קיצבת ילד(י)    115.00       NaN
31  25/02/2026  ביטוח לאומי חד פעמי(י)    219.00       NaN

In [14]:
from etl_sources.mizrachi_reader import load_mizrachi_tables
import pandas as pd

# Canonical output date format for YNAB-bound data.
# Scope: shared project constant (belongs in a common constants module when stabilized).
YNAB_OUTPUT_DATE_FORMAT = "%d/%m/%Y"

# Accepted input date formats for Mizrachi exports.
# Scope: source-specific parser constant (belongs in Mizrachi parser module).
MIZRACHI_INPUT_DATE_FORMATS = ("%d/%m/%y", "%d/%m/%Y")

# Column translation from Hebrew source headers to canonical/intermediate names.
# Scope: keep source-specific until reused by multiple Hebrew sources.
HEBREW_TO_CANONICAL_COLUMN_MAP = {
    'תאריך': 'Date',
    'סוג תנועה': 'Payee',
    'זכות': 'Inflow',
    'חובה': 'Outflow'
}


def _dedupe_column_names(names: list[str]) -> list[str]:
    seen_counts: dict[str, int] = {}
    deduped: list[str] = []

    for name in names:
        count = seen_counts.get(name, 0) + 1
        seen_counts[name] = count
        deduped.append(name if count == 1 else f"{name}_{count}")

    return deduped


def parse_mizrachi_dates(
    raw_date_col: pd.Series, date_formats: tuple[str, ...] = MIZRACHI_INPUT_DATE_FORMATS
) -> pd.Series:
    # Clean raw values
    s = raw_date_col.astype(str).str.strip()
    s = s.replace({"": pd.NA, "nan": pd.NA, "None": pd.NA})
    parsed = pd.to_datetime(s, format=date_formats[0], errors="coerce")
    # Second pass (only failed rows): dd/mm/yyyy
    missing = parsed.isna()
    parsed.loc[missing] = pd.to_datetime(
        s.loc[missing],
        format=date_formats[0],
        errors="coerce",
    )
    return parsed


def apply_detected_header(df: pd.DataFrame, header_row_idx: int) -> pd.DataFrame:
    if df.empty:
        return df.copy()

    if header_row_idx < 0 or header_row_idx >= len(df):
        raise ValueError(
            f"Detected header_row_idx {header_row_idx} is out of bounds for dataframe with {len(df)} rows."
        )

    raw_header = df.iloc[header_row_idx, :]
    cleaned_header = []
    for col_idx, value in enumerate(raw_header):
        if pd.isna(value):
            cleaned_header.append(f"unnamed_{col_idx}")
            continue

        header_name = str(value).strip()
        cleaned_header.append(header_name or f"unnamed_{col_idx}")

    normalized_columns = _dedupe_column_names(cleaned_header)
    normalized_df = df.iloc[header_row_idx + 1 :].copy().reset_index(drop=True)
    normalized_df.columns = normalized_columns
    return normalized_df


def detect_header_row_mizrachi_case(
    df: pd.DataFrame,
    default_row: int = 3,
    probe_rows: int = 1,
) -> int:
    """
    Heuristic:
    1) Find first column that has NaN in the first `probe_rows`.
    2) In that column, return first non-null row index.
    3) If no signal found, return default_row.
    """
    if df.empty:
        return default_row
    # Step 1: columns that look like your Mizrachi signature
    candidate_cols = [
        col for col in df.columns
        if df[col].iloc[:probe_rows].isna().any()
    ]
    # Step 2: find first non-null row in first matching column
    for col in candidate_cols:
        first_valid = df[col].first_valid_index()  # returns None if all null
        if first_valid is not None:
            return int(first_valid)
    return default_row

def main(path_to_folder: str, dates_range: tuple[str, str] | None = None) -> None:
    loaded_tables = load_mizrachi_tables(folder=path_to_folder, recursive=False)
    print(f"Loaded files: {len(loaded_tables)}")

    for table in loaded_tables:
        print(f"\nFile: {table.path.name} ({table.extension})")
        df_pending = table.dataframe
        print(df_pending.head())

    if dates_range:
        print(f"Requested date range: {dates_range[0]} -> {dates_range[1]}")
    

    # Detect header row in Mizrachi export via NaN-first-row signature.
    header_row_idx = detect_header_row_mizrachi_case(df_pending)

    df_pending = apply_detected_header(df_pending, header_row_idx)

    # find last footer of dataframe  using date column (non date values) or     
    # dataframe has been aligned to the header row

    # translating columns names using global mapping (for this project)
    df_pending.columns = df_pending.columns.map(HEBREW_TO_CANONICAL_COLUMN_MAP)
    
    # Align dates to dd/mm/YYYY format + drop rows with invalid dates
    parsed_dates = parse_mizrachi_dates(df_pending["Date"])
    # 2) Keep only valid date rows
    valid_mask = parsed_dates.notna()
    df_pending = df_pending.loc[valid_mask].copy()
    # 3) Format to dd/mm/yyyy
    df_pending["Date"] = parsed_dates.loc[valid_mask].dt.strftime(YNAB_OUTPUT_DATE_FORMAT)

    # Keep only the mapped columns if exist
    df_pending = df_pending[
        [column for column in HEBREW_TO_CANONICAL_COLUMN_MAP.values() if column in df_pending.columns]
    ]


    #  
# STEP: parse date
# STEP: split inflow/outflow
# TODO: handle installment rows


if __name__ == "__main__":
    path_to_folder = r'C:\Users\shai\Documents\personal\personal_projects\ynab-israel-consolidator\private_data\incoming\bank_mizrachi'
    dates_range = ("01/01/2026", "01/03/2026")
    main(path_to_folder=path_to_folder, dates_range=dates_range)

Loaded files: 1

File: AccountActivity (1).xls (.xls)
                0          1                    2               3       4  \
0    יתרה בחשבון:   29856.69             לתאריך -  05/03/26 23:15     NaN
1    מסגרת אשראי:   20000.00                  NaN             NaN     NaN
2  תנועות אחרונות        NaN                  NaN             NaN     NaN
3           תאריך  תאריך ערך            סוג תנועה            זכות    חובה
4        10/12/25        NaN  ביצוע הוראת קבע (י)             NaN  600.00

           5       6            __source_file  \
0        NaN     NaN  AccountActivity (1).xls
1        NaN     NaN  AccountActivity (1).xls
2        NaN     NaN  AccountActivity (1).xls
3  יתרה בש"ח  אסמכתא  AccountActivity (1).xls
4    9451.53      29  AccountActivity (1).xls

                                       __source_path __source_ext  \
0  C:\Users\shai\Documents\personal\personal_proj...         .xls
1  C:\Users\shai\Documents\personal\personal_proj...         .xls
2  C:\Users\shai\Documents\personal\personal_proj...         .xls
3  C:\Users\shai\Documents\personal\personal_proj...         .xls
4  C:\Users\shai\Documents\personal\personal_proj...         .xls

                __source_rule
0  mizrachi_read_html_table_1
1  mizrachi_read_html_table_1
2  mizrachi_read_html_table_1
3  mizrachi_read_html_table_1
4  mizrachi_read_html_table_1
Requested date range: 01/01/2026 -> 01/03/2026

In [15]:
loaded_tables = load_mizrachi_tables(folder=path_to_folder, recursive=False)
print(f"Loaded files: {len(loaded_tables)}")

for table in loaded_tables:
    print(f"\nFile: {table.path.name} ({table.extension})")
    df_pending = table.dataframe
    print(df_pending.head())

if dates_range:
    print(f"Requested date range: {dates_range[0]} -> {dates_range[1]}")


# Detect header row in Mizrachi export via NaN-first-row signature.
header_row_idx = detect_header_row_mizrachi_case(df_pending)

df_pending = apply_detected_header(df_pending, header_row_idx)

# find last footer of dataframe  using date column (non date values) or     
# dataframe has been aligned to the header row

# translating columns names using global mapping (for this project)
df_pending.columns = df_pending.columns.map(HEBREW_TO_CANONICAL_COLUMN_MAP)

# Align dates to dd/mm/YYYY format + drop rows with invalid dates
parsed_dates = parse_mizrachi_dates(df_pending["Date"])
# 2) Keep only valid date rows
valid_mask = parsed_dates.notna()
df_pending = df_pending.loc[valid_mask].copy()
# 3) Format to dd/mm/yyyy
df_pending["Date"] = parsed_dates.loc[valid_mask].dt.strftime(YNAB_OUTPUT_DATE_FORMAT)

# Keep only the mapped columns if exist
df_pending = df_pending[
    [column for column in HEBREW_TO_CANONICAL_COLUMN_MAP.values() if column in df_pending.columns]
]

Loaded files: 1

File: AccountActivity (1).xls (.xls)
                0          1                    2               3       4  \
0    יתרה בחשבון:   29856.69             לתאריך -  05/03/26 23:15     NaN
1    מסגרת אשראי:   20000.00                  NaN             NaN     NaN
2  תנועות אחרונות        NaN                  NaN             NaN     NaN
3           תאריך  תאריך ערך            סוג תנועה            זכות    חובה
4        10/12/25        NaN  ביצוע הוראת קבע (י)             NaN  600.00

           5       6            __source_file  \
0        NaN     NaN  AccountActivity (1).xls
1        NaN     NaN  AccountActivity (1).xls
2        NaN     NaN  AccountActivity (1).xls
3  יתרה בש"ח  אסמכתא  AccountActivity (1).xls
4    9451.53      29  AccountActivity (1).xls

                                       __source_path __source_ext  \
0  C:\Users\shai\Documents\personal\personal_proj...         .xls
1  C:\Users\shai\Documents\personal\personal_proj...         .xls
2  C:\Users\shai\Documents\personal\personal_proj...         .xls
3  C:\Users\shai\Documents\personal\personal_proj...         .xls
4  C:\Users\shai\Documents\personal\personal_proj...         .xls

                __source_rule
0  mizrachi_read_html_table_1
1  mizrachi_read_html_table_1
2  mizrachi_read_html_table_1
3  mizrachi_read_html_table_1
4  mizrachi_read_html_table_1
Requested date range: 01/01/2026 -> 01/03/2026

In [16]:
df_pending

          Date                   Payee    Inflow   Outflow
0   10/12/2025     ביצוע הוראת קבע (י)       NaN    600.00
1   10/12/2025       הרשאה ישראכרט (י)       NaN   2874.04
2   10/12/2025  מור גמל ופנסיה בע"מ(י)       NaN   1000.00
3   11/12/2025        טן חברה לדלק (י)       NaN    481.84
4   15/12/2025  הרשאה מקס איט פיננס(י)       NaN   7868.72
5   16/12/2025  זיכוי - בנק הפועלים(י)   3000.00       NaN
6   21/12/2025  ב. לאומי- קיצבת ילד(י)    112.00       NaN
7   01/01/2026              ריבית עו"ש     13.72       NaN
8   04/01/2026  זיכוי - בנק הפועלים(י)   3200.00       NaN
9   04/01/2026  זיכוי - בנק הפועלים(י)   5000.00       NaN
10  11/01/2026     ביצוע הוראת קבע (י)       NaN    600.00
11  11/01/2026       הרשאה ישראכרט (י)       NaN   2504.63
12  11/01/2026        טן חברה לדלק (י)       NaN    476.61
13  11/01/2026  מור גמל ופנסיה בע"מ(י)       NaN    800.00
14  12/01/2026  זיכוי - בנק הפועלים(י)   4990.00       NaN
15  15/01/2026  הרשאה מקס איט פיננס(י)       NaN   5875.55
16  20/01/2026  ב. לאומי- קיצבת ילד(י)    115.00       NaN
17  01/02/2026  זיכוי - בנק הפועלים(י)   5000.00       NaN
18  04/02/2026  זיכוי - בנק הפועלים(י)   5000.00       NaN
19  06/02/2026  הרשאה מקס איט פיננס(י)       NaN     62.78
20  08/02/2026  זיכוי - בנק הפועלים(י)  17000.00       NaN
21  10/02/2026  ביטוח לאומי חד פעמי(י)  20315.00       NaN
22  10/02/2026     ביצוע הוראת קבע (י)       NaN    600.00
23  10/02/2026       הרשאה ישראכרט (י)       NaN   3427.00
24  10/02/2026  הרשאה מקס איט פיננס(י)       NaN    500.00
25  10/02/2026  מור גמל ופנסיה בע"מ(י)       NaN    800.00
26  13/02/2026  ביטוח לאומי חד פעמי(י)    946.00       NaN
27  13/02/2026      העברה באינטרנט (י)       NaN   2000.00
28  15/02/2026  הרשאה מקס איט פיננס(י)       NaN  12989.39
29  15/02/2026      העברה באינטרנט (י)       NaN   1400.00
30  20/02/2026  ב. לאומי- קיצבת ילד(י)    115.00       NaN
31  25/02/2026  ביטוח לאומי חד פעמי(י)    219.00       NaN

In [17]:
from etl_sources.mizrachi_reader import load_mizrachi_tables
from etl_sources.constants import YNAB_OUTPUT_DATE_FORMAT
from etl_sources.mizrachi_constants import (
    MIZRACHI_HEBREW_TO_CANONICAL_COLUMN_MAP,
    MIZRACHI_INPUT_DATE_FORMAT,
)
import pandas as pd


def _dedupe_column_names(names: list[str]) -> list[str]:
    seen_counts: dict[str, int] = {}
    deduped: list[str] = []

    for name in names:
        count = seen_counts.get(name, 0) + 1
        seen_counts[name] = count
        deduped.append(name if count == 1 else f"{name}_{count}")

    return deduped


def parse_mizrachi_dates(
    raw_date_col: pd.Series, date_format: str = MIZRACHI_INPUT_DATE_FORMAT
) -> pd.Series:
    # Clean raw values
    s = raw_date_col.astype(str).str.strip()
    s = s.replace({"": pd.NA, "nan": pd.NA, "None": pd.NA})
    parsed = pd.to_datetime(s, format=date_format, errors="coerce")
    # Second pass (only failed rows): dd/mm/yyyy
    missing = parsed.isna()
    parsed.loc[missing] = pd.to_datetime(
        s.loc[missing],
        format=date_format,
        errors="coerce",
    )
    return parsed


def apply_detected_header(df: pd.DataFrame, header_row_idx: int) -> pd.DataFrame:
    if df.empty:
        return df.copy()

    if header_row_idx < 0 or header_row_idx >= len(df):
        raise ValueError(
            f"Detected header_row_idx {header_row_idx} is out of bounds for dataframe with {len(df)} rows."
        )

    raw_header = df.iloc[header_row_idx, :]
    cleaned_header = []
    for col_idx, value in enumerate(raw_header):
        if pd.isna(value):
            cleaned_header.append(f"unnamed_{col_idx}")
            continue

        header_name = str(value).strip()
        cleaned_header.append(header_name or f"unnamed_{col_idx}")

    normalized_columns = _dedupe_column_names(cleaned_header)
    normalized_df = df.iloc[header_row_idx + 1 :].copy().reset_index(drop=True)
    normalized_df.columns = normalized_columns
    return normalized_df


def detect_header_row_mizrachi_case(
    df: pd.DataFrame,
    default_row: int = 3,
    probe_rows: int = 1,
) -> int:
    """
    Heuristic:
    1) Find first column that has NaN in the first `probe_rows`.
    2) In that column, return first non-null row index.
    3) If no signal found, return default_row.
    """
    if df.empty:
        return default_row
    # Step 1: columns that look like your Mizrachi signature
    candidate_cols = [
        col for col in df.columns
        if df[col].iloc[:probe_rows].isna().any()
    ]
    # Step 2: find first non-null row in first matching column
    for col in candidate_cols:
        first_valid = df[col].first_valid_index()  # returns None if all null
        if first_valid is not None:
            return int(first_valid)
    return default_row

def main(path_to_folder: str, dates_range: tuple[str, str] | None = None) -> None:
    loaded_tables = load_mizrachi_tables(folder=path_to_folder, recursive=False)
    print(f"Loaded files: {len(loaded_tables)}")

    for table in loaded_tables:
        print(f"\nFile: {table.path.name} ({table.extension})")
        df_pending = table.dataframe
        print(df_pending.head())

    if dates_range:
        print(f"Requested date range: {dates_range[0]} -> {dates_range[1]}")
    

    # Detect header row in Mizrachi export via NaN-first-row signature.
    header_row_idx = detect_header_row_mizrachi_case(df_pending)

    df_pending = apply_detected_header(df_pending, header_row_idx)

    # find last footer of dataframe  using date column (non date values) or     
    # dataframe has been aligned to the header row

    # translating columns names using global mapping (for this project)
    df_pending.columns = df_pending.columns.map(MIZRACHI_HEBREW_TO_CANONICAL_COLUMN_MAP)
    
    # Align dates to dd/mm/YYYY format + drop rows with invalid dates
    parsed_dates = parse_mizrachi_dates(df_pending["Date"])
    # 2) Keep only valid date rows
    valid_mask = parsed_dates.notna()
    df_pending = df_pending.loc[valid_mask].copy()
    # 3) Format to dd/mm/yyyy
    df_pending["Date"] = parsed_dates.loc[valid_mask].dt.strftime(YNAB_OUTPUT_DATE_FORMAT)

    # Keep only the mapped columns if exist
    df_pending = df_pending[
        [
            column
            for column in MIZRACHI_HEBREW_TO_CANONICAL_COLUMN_MAP.values()
            if column in df_pending.columns
        ]
    ]


    #  
# STEP: parse date
# STEP: split inflow/outflow
# TODO: handle installment rows


if __name__ == "__main__":
    path_to_folder = r'C:\Users\shai\Documents\personal\personal_projects\ynab-israel-consolidator\private_data\incoming\bank_mizrachi'
    dates_range = ("01/01/2026", "01/03/2026")
    main(path_to_folder=path_to_folder, dates_range=dates_range)

Loaded files: 1

File: AccountActivity (1).xls (.xls)
                0          1                    2               3       4  \
0    יתרה בחשבון:   29856.69             לתאריך -  05/03/26 23:15     NaN
1    מסגרת אשראי:   20000.00                  NaN             NaN     NaN
2  תנועות אחרונות        NaN                  NaN             NaN     NaN
3           תאריך  תאריך ערך            סוג תנועה            זכות    חובה
4        10/12/25        NaN  ביצוע הוראת קבע (י)             NaN  600.00

           5       6            __source_file  \
0        NaN     NaN  AccountActivity (1).xls
1        NaN     NaN  AccountActivity (1).xls
2        NaN     NaN  AccountActivity (1).xls
3  יתרה בש"ח  אסמכתא  AccountActivity (1).xls
4    9451.53      29  AccountActivity (1).xls

                                       __source_path __source_ext  \
0  C:\Users\shai\Documents\personal\personal_proj...         .xls
1  C:\Users\shai\Documents\personal\personal_proj...         .xls
2  C:\Users\shai\Documents\personal\personal_proj...         .xls
3  C:\Users\shai\Documents\personal\personal_proj...         .xls
4  C:\Users\shai\Documents\personal\personal_proj...         .xls

                __source_rule
0  mizrachi_read_html_table_1
1  mizrachi_read_html_table_1
2  mizrachi_read_html_table_1
3  mizrachi_read_html_table_1
4  mizrachi_read_html_table_1
Requested date range: 01/01/2026 -> 01/03/2026

In [18]:
loaded_tables = load_mizrachi_tables(folder=path_to_folder, recursive=False)
print(f"Loaded files: {len(loaded_tables)}")

for table in loaded_tables:
    print(f"\nFile: {table.path.name} ({table.extension})")
    df_pending = table.dataframe
    print(df_pending.head())

if dates_range:
    print(f"Requested date range: {dates_range[0]} -> {dates_range[1]}")


# Detect header row in Mizrachi export via NaN-first-row signature.
header_row_idx = detect_header_row_mizrachi_case(df_pending)

df_pending = apply_detected_header(df_pending, header_row_idx)

# find last footer of dataframe  using date column (non date values) or     
# dataframe has been aligned to the header row

# translating columns names using global mapping (for this project)
df_pending.columns = df_pending.columns.map(MIZRACHI_HEBREW_TO_CANONICAL_COLUMN_MAP)

# Align dates to dd/mm/YYYY format + drop rows with invalid dates
parsed_dates = parse_mizrachi_dates(df_pending["Date"])
# 2) Keep only valid date rows
valid_mask = parsed_dates.notna()
df_pending = df_pending.loc[valid_mask].copy()
# 3) Format to dd/mm/yyyy
df_pending["Date"] = parsed_dates.loc[valid_mask].dt.strftime(YNAB_OUTPUT_DATE_FORMAT)

# Keep only the mapped columns if exist
df_pending = df_pending[
    [
        column
        for column in MIZRACHI_HEBREW_TO_CANONICAL_COLUMN_MAP.values()
        if column in df_pending.columns
    ]
]

Loaded files: 1

File: AccountActivity (1).xls (.xls)
                0          1                    2               3       4  \
0    יתרה בחשבון:   29856.69             לתאריך -  05/03/26 23:15     NaN
1    מסגרת אשראי:   20000.00                  NaN             NaN     NaN
2  תנועות אחרונות        NaN                  NaN             NaN     NaN
3           תאריך  תאריך ערך            סוג תנועה            זכות    חובה
4        10/12/25        NaN  ביצוע הוראת קבע (י)             NaN  600.00

           5       6            __source_file  \
0        NaN     NaN  AccountActivity (1).xls
1        NaN     NaN  AccountActivity (1).xls
2        NaN     NaN  AccountActivity (1).xls
3  יתרה בש"ח  אסמכתא  AccountActivity (1).xls
4    9451.53      29  AccountActivity (1).xls

                                       __source_path __source_ext  \
0  C:\Users\shai\Documents\personal\personal_proj...         .xls
1  C:\Users\shai\Documents\personal\personal_proj...         .xls
2  C:\Users\shai\Documents\personal\personal_proj...         .xls
3  C:\Users\shai\Documents\personal\personal_proj...         .xls
4  C:\Users\shai\Documents\personal\personal_proj...         .xls

                __source_rule
0  mizrachi_read_html_table_1
1  mizrachi_read_html_table_1
2  mizrachi_read_html_table_1
3  mizrachi_read_html_table_1
4  mizrachi_read_html_table_1
Requested date range: 01/01/2026 -> 01/03/2026

In [19]:
df_pending

          Date                   Payee    Inflow   Outflow
0   10/12/2025     ביצוע הוראת קבע (י)       NaN    600.00
1   10/12/2025       הרשאה ישראכרט (י)       NaN   2874.04
2   10/12/2025  מור גמל ופנסיה בע"מ(י)       NaN   1000.00
3   11/12/2025        טן חברה לדלק (י)       NaN    481.84
4   15/12/2025  הרשאה מקס איט פיננס(י)       NaN   7868.72
5   16/12/2025  זיכוי - בנק הפועלים(י)   3000.00       NaN
6   21/12/2025  ב. לאומי- קיצבת ילד(י)    112.00       NaN
7   01/01/2026              ריבית עו"ש     13.72       NaN
8   04/01/2026  זיכוי - בנק הפועלים(י)   3200.00       NaN
9   04/01/2026  זיכוי - בנק הפועלים(י)   5000.00       NaN
10  11/01/2026     ביצוע הוראת קבע (י)       NaN    600.00
11  11/01/2026       הרשאה ישראכרט (י)       NaN   2504.63
12  11/01/2026        טן חברה לדלק (י)       NaN    476.61
13  11/01/2026  מור גמל ופנסיה בע"מ(י)       NaN    800.00
14  12/01/2026  זיכוי - בנק הפועלים(י)   4990.00       NaN
15  15/01/2026  הרשאה מקס איט פיננס(י)       NaN   5875.55
16  20/01/2026  ב. לאומי- קיצבת ילד(י)    115.00       NaN
17  01/02/2026  זיכוי - בנק הפועלים(י)   5000.00       NaN
18  04/02/2026  זיכוי - בנק הפועלים(י)   5000.00       NaN
19  06/02/2026  הרשאה מקס איט פיננס(י)       NaN     62.78
20  08/02/2026  זיכוי - בנק הפועלים(י)  17000.00       NaN
21  10/02/2026  ביטוח לאומי חד פעמי(י)  20315.00       NaN
22  10/02/2026     ביצוע הוראת קבע (י)       NaN    600.00
23  10/02/2026       הרשאה ישראכרט (י)       NaN   3427.00
24  10/02/2026  הרשאה מקס איט פיננס(י)       NaN    500.00
25  10/02/2026  מור גמל ופנסיה בע"מ(י)       NaN    800.00
26  13/02/2026  ביטוח לאומי חד פעמי(י)    946.00       NaN
27  13/02/2026      העברה באינטרנט (י)       NaN   2000.00
28  15/02/2026  הרשאה מקס איט פיננס(י)       NaN  12989.39
29  15/02/2026      העברה באינטרנט (י)       NaN   1400.00
30  20/02/2026  ב. לאומי- קיצבת ילד(י)    115.00       NaN
31  25/02/2026  ביטוח לאומי חד פעמי(י)    219.00       NaN

In [20]:
"""Prototype pipeline for normalizing Mizrachi exports toward YNAB shape."""

# Imports
from etl_sources.mizrachi_reader import load_mizrachi_tables
from etl_sources.constants import YNAB_OUTPUT_DATE_FORMAT
from etl_sources.mizrachi_constants import (
    MIZRACHI_HEBREW_TO_CANONICAL_COLUMN_MAP,
    MIZRACHI_INPUT_DATE_FORMAT,
)
import pandas as pd

# Orchestration
def main(path_to_folder: str, dates_range: tuple[str, str] | None = None) -> None:
    loaded_tables = load_mizrachi_tables(folder=path_to_folder, recursive=False)
    print(f"Loaded files: {len(loaded_tables)}")

    for table in loaded_tables:
        print(f"\nFile: {table.path.name} ({table.extension})")
        df_pending = table.dataframe
        print(df_pending.head())

    if dates_range:
        print(f"Requested date range: {dates_range[0]} -> {dates_range[1]}")

    # Detect header row in Mizrachi export via NaN-first-row signature.
    header_row_idx = detect_mizrachi_header_row(df_pending)

    df_pending = apply_detected_header(df_pending, header_row_idx)

    # find last footer of dataframe  using date column (non date values) or
    # dataframe has been aligned to the header row

    # translating columns names using global mapping (for this project)
    df_pending.columns = df_pending.columns.map(MIZRACHI_HEBREW_TO_CANONICAL_COLUMN_MAP)

    # Align dates to dd/mm/YYYY format + drop rows with invalid dates
    parsed_dates = parse_mizrachi_dates(df_pending["Date"])
    # 2) Keep only valid date rows
    valid_mask = parsed_dates.notna()
    df_pending = df_pending.loc[valid_mask].copy()
    # 3) Format to dd/mm/yyyy
    df_pending["Date"] = parsed_dates.loc[valid_mask].dt.strftime(YNAB_OUTPUT_DATE_FORMAT)

    # Keep only the mapped columns if exist
    df_pending = df_pending[
        [
            column
            for column in MIZRACHI_HEBREW_TO_CANONICAL_COLUMN_MAP.values()
            if column in df_pending.columns
        ]
    ]

    # Prototype next steps:
    # - Split inflow/outflow to YNAB-compatible amount fields.
    # - Add installment-specific handling.

# Pipeline steps
# Header detection
def detect_mizrachi_header_row(
    df: pd.DataFrame,
    default_row: int = 3,
    probe_rows: int = 1,
) -> int:
    """
    Heuristic:
    1) Find first column that has NaN in the first `probe_rows`.
    2) In that column, return first non-null row index.
    3) If no signal found, return default_row.
    """
    if df.empty:
        return default_row
    # Step 1: columns that look like your Mizrachi signature
    candidate_cols = [
        col for col in df.columns
        if df[col].iloc[:probe_rows].isna().any()
    ]
    # Step 2: find first non-null row in first matching column
    for col in candidate_cols:
        first_valid = df[col].first_valid_index()  # returns None if all null
        if first_valid is not None:
            return int(first_valid)
    return default_row


def detect_header_row_mizrachi_case(
    df: pd.DataFrame,
    default_row: int = 3,
    probe_rows: int = 1,
) -> int:
    """Backward-compatible alias for detect_mizrachi_header_row."""
    return detect_mizrachi_header_row(df, default_row=default_row, probe_rows=probe_rows)


# Header application
def apply_detected_header(df: pd.DataFrame, header_row_idx: int) -> pd.DataFrame:
    if df.empty:
        return df.copy()

    if header_row_idx < 0 or header_row_idx >= len(df):
        raise ValueError(
            f"Detected header_row_idx {header_row_idx} is out of bounds for dataframe with {len(df)} rows."
        )

    raw_header = df.iloc[header_row_idx, :]
    cleaned_header = []
    for col_idx, value in enumerate(raw_header):
        if pd.isna(value):
            cleaned_header.append(f"unnamed_{col_idx}")
            continue

        header_name = str(value).strip()
        cleaned_header.append(header_name or f"unnamed_{col_idx}")

    normalized_columns = _dedupe_column_names(cleaned_header)
    normalized_df = df.iloc[header_row_idx + 1 :].copy().reset_index(drop=True)
    normalized_df.columns = normalized_columns
    return normalized_df


# Date parsing
def parse_mizrachi_dates(
    raw_date_col: pd.Series, date_format: str = MIZRACHI_INPUT_DATE_FORMAT
) -> pd.Series:
    # Clean raw values
    s = raw_date_col.astype(str).str.strip()
    s = s.replace({"": pd.NA, "nan": pd.NA, "None": pd.NA})
    parsed = pd.to_datetime(s, format=date_format, errors="coerce")
    # Second pass (only failed rows): dd/mm/yyyy
    missing = parsed.isna()
    parsed.loc[missing] = pd.to_datetime(
        s.loc[missing],
        format=date_format,
        errors="coerce",
    )
    return parsed

# Helpers
def _dedupe_column_names(names: list[str]) -> list[str]:
    seen_counts: dict[str, int] = {}
    deduped: list[str] = []

    for name in names:
        count = seen_counts.get(name, 0) + 1
        seen_counts[name] = count
        deduped.append(name if count == 1 else f"{name}_{count}")

    return deduped


# Entry point
if __name__ == "__main__":
    path_to_folder = r'C:\Users\shai\Documents\personal\personal_projects\ynab-israel-consolidator\private_data\incoming\bank_mizrachi'
    dates_range = ("01/01/2026", "01/03/2026")
    main(path_to_folder=path_to_folder, dates_range=dates_range)

Loaded files: 1

File: AccountActivity (1).xls (.xls)
                0          1                    2               3       4  \
0    יתרה בחשבון:   29856.69             לתאריך -  05/03/26 23:15     NaN
1    מסגרת אשראי:   20000.00                  NaN             NaN     NaN
2  תנועות אחרונות        NaN                  NaN             NaN     NaN
3           תאריך  תאריך ערך            סוג תנועה            זכות    חובה
4        10/12/25        NaN  ביצוע הוראת קבע (י)             NaN  600.00

           5       6            __source_file  \
0        NaN     NaN  AccountActivity (1).xls
1        NaN     NaN  AccountActivity (1).xls
2        NaN     NaN  AccountActivity (1).xls
3  יתרה בש"ח  אסמכתא  AccountActivity (1).xls
4    9451.53      29  AccountActivity (1).xls

                                       __source_path __source_ext  \
0  C:\Users\shai\Documents\personal\personal_proj...         .xls
1  C:\Users\shai\Documents\personal\personal_proj...         .xls
2  C:\Users\shai\Documents\personal\personal_proj...         .xls
3  C:\Users\shai\Documents\personal\personal_proj...         .xls
4  C:\Users\shai\Documents\personal\personal_proj...         .xls

                __source_rule
0  mizrachi_read_html_table_1
1  mizrachi_read_html_table_1
2  mizrachi_read_html_table_1
3  mizrachi_read_html_table_1
4  mizrachi_read_html_table_1
Requested date range: 01/01/2026 -> 01/03/2026

In [21]:
loaded_tables = load_mizrachi_tables(folder=path_to_folder, recursive=False)
print(f"Loaded files: {len(loaded_tables)}")

for table in loaded_tables:
    print(f"\nFile: {table.path.name} ({table.extension})")
    df_pending = table.dataframe
    print(df_pending.head())

if dates_range:
    print(f"Requested date range: {dates_range[0]} -> {dates_range[1]}")

# Detect header row in Mizrachi export via NaN-first-row signature.
header_row_idx = detect_mizrachi_header_row(df_pending)

df_pending = apply_detected_header(df_pending, header_row_idx)

# find last footer of dataframe  using date column (non date values) or
# dataframe has been aligned to the header row

# translating columns names using global mapping (for this project)
df_pending.columns = df_pending.columns.map(MIZRACHI_HEBREW_TO_CANONICAL_COLUMN_MAP)

# Align dates to dd/mm/YYYY format + drop rows with invalid dates
parsed_dates = parse_mizrachi_dates(df_pending["Date"])
# 2) Keep only valid date rows
valid_mask = parsed_dates.notna()
df_pending = df_pending.loc[valid_mask].copy()
# 3) Format to dd/mm/yyyy
df_pending["Date"] = parsed_dates.loc[valid_mask].dt.strftime(YNAB_OUTPUT_DATE_FORMAT)

# Keep only the mapped columns if exist
df_pending = df_pending[
    [
        column
        for column in MIZRACHI_HEBREW_TO_CANONICAL_COLUMN_MAP.values()
        if column in df_pending.columns
    ]
]

Loaded files: 1

File: AccountActivity (1).xls (.xls)
                0          1                    2               3       4  \
0    יתרה בחשבון:   29856.69             לתאריך -  05/03/26 23:15     NaN
1    מסגרת אשראי:   20000.00                  NaN             NaN     NaN
2  תנועות אחרונות        NaN                  NaN             NaN     NaN
3           תאריך  תאריך ערך            סוג תנועה            זכות    חובה
4        10/12/25        NaN  ביצוע הוראת קבע (י)             NaN  600.00

           5       6            __source_file  \
0        NaN     NaN  AccountActivity (1).xls
1        NaN     NaN  AccountActivity (1).xls
2        NaN     NaN  AccountActivity (1).xls
3  יתרה בש"ח  אסמכתא  AccountActivity (1).xls
4    9451.53      29  AccountActivity (1).xls

                                       __source_path __source_ext  \
0  C:\Users\shai\Documents\personal\personal_proj...         .xls
1  C:\Users\shai\Documents\personal\personal_proj...         .xls
2  C:\Users\shai\Documents\personal\personal_proj...         .xls
3  C:\Users\shai\Documents\personal\personal_proj...         .xls
4  C:\Users\shai\Documents\personal\personal_proj...         .xls

                __source_rule
0  mizrachi_read_html_table_1
1  mizrachi_read_html_table_1
2  mizrachi_read_html_table_1
3  mizrachi_read_html_table_1
4  mizrachi_read_html_table_1
Requested date range: 01/01/2026 -> 01/03/2026

In [22]:
df_pending

          Date                   Payee    Inflow   Outflow
0   10/12/2025     ביצוע הוראת קבע (י)       NaN    600.00
1   10/12/2025       הרשאה ישראכרט (י)       NaN   2874.04
2   10/12/2025  מור גמל ופנסיה בע"מ(י)       NaN   1000.00
3   11/12/2025        טן חברה לדלק (י)       NaN    481.84
4   15/12/2025  הרשאה מקס איט פיננס(י)       NaN   7868.72
5   16/12/2025  זיכוי - בנק הפועלים(י)   3000.00       NaN
6   21/12/2025  ב. לאומי- קיצבת ילד(י)    112.00       NaN
7   01/01/2026              ריבית עו"ש     13.72       NaN
8   04/01/2026  זיכוי - בנק הפועלים(י)   3200.00       NaN
9   04/01/2026  זיכוי - בנק הפועלים(י)   5000.00       NaN
10  11/01/2026     ביצוע הוראת קבע (י)       NaN    600.00
11  11/01/2026       הרשאה ישראכרט (י)       NaN   2504.63
12  11/01/2026        טן חברה לדלק (י)       NaN    476.61
13  11/01/2026  מור גמל ופנסיה בע"מ(י)       NaN    800.00
14  12/01/2026  זיכוי - בנק הפועלים(י)   4990.00       NaN
15  15/01/2026  הרשאה מקס איט פיננס(י)       NaN   5875.55
16  20/01/2026  ב. לאומי- קיצבת ילד(י)    115.00       NaN
17  01/02/2026  זיכוי - בנק הפועלים(י)   5000.00       NaN
18  04/02/2026  זיכוי - בנק הפועלים(י)   5000.00       NaN
19  06/02/2026  הרשאה מקס איט פיננס(י)       NaN     62.78
20  08/02/2026  זיכוי - בנק הפועלים(י)  17000.00       NaN
21  10/02/2026  ביטוח לאומי חד פעמי(י)  20315.00       NaN
22  10/02/2026     ביצוע הוראת קבע (י)       NaN    600.00
23  10/02/2026       הרשאה ישראכרט (י)       NaN   3427.00
24  10/02/2026  הרשאה מקס איט פיננס(י)       NaN    500.00
25  10/02/2026  מור גמל ופנסיה בע"מ(י)       NaN    800.00
26  13/02/2026  ביטוח לאומי חד פעמי(י)    946.00       NaN
27  13/02/2026      העברה באינטרנט (י)       NaN   2000.00
28  15/02/2026  הרשאה מקס איט פיננס(י)       NaN  12989.39
29  15/02/2026      העברה באינטרנט (י)       NaN   1400.00
30  20/02/2026  ב. לאומי- קיצבת ילד(י)    115.00       NaN
31  25/02/2026  ביטוח לאומי חד פעמי(י)    219.00       NaN